#!/usr/bin/env python3
"""Generate the two-level clip browser under the OOD charts.

Four suites on top, and inside each one three views: the data we collect, and
the two perturbations we are evaluated under. The perturbations were previously
three column-pairs of one very wide row, six clips abreast -- which fit, but
only by shrinking every clip to a thumbnail. Splitting them onto their own
buttons trades one crowded grid for three roomy ones and costs the reader a
click they were making with their eyes anyway.

Row counts and labels live in the tables below; re-run after changing them:

    python3 tools/make_ood_grid.py

It rewrites the marked block in index.html in place.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "index.html")

BEGIN = "      <!-- >>> OOD GRID: generated by tools/make_ood_grid.py >>> -->"
END = "      <!-- <<< OOD GRID <<< -->"

SUITES = [("object", "LIBERO-Object"), ("spatial", "LIBERO-Spatial"),
          ("goal", "LIBERO-Goal"), ("10", "LIBERO-10")]

# key, button label, per-row clip labels, whether rows name a perturbed task
VIEWS = [
    ("sw", "SkillWeaver Data", ["SW 1", "SW 2", "SW 3"], False),
    ("pos", "Position Perturbation", ["GT only", "GT + SW Data"], False),
    ("task", "Task Perturbation", ["GT only", "GT + SW Data"], True),
]

TASKS = 4


def cell(label, ind):
    p = "  " * ind
    return [p + '<div class="media media--placeholder media--cell">',
            p + '  <svg class="placeholder__mark" viewBox="0 0 48 48" aria-hidden="true">',
            p + '    <circle class="ph-node" cx="24" cy="24" r="20" />',
            p + '    <path class="ph-play" d="M19.5,15 L33,24 L19.5,33 Z" />',
            p + '  </svg>',
            p + '  <p class="placeholder__text">%s</p>' % label,
            p + '</div>']


def view_panel(suite, key, label, clips, renamed, first):
    pid = "panel-ood-%s-%s" % (suite, key)
    tid = "tab-ood-%s-%s" % (suite, key)
    L = ['<div class="panel" id="%s" role="tabpanel" aria-labelledby="%s"%s>'
         % (pid, tid, "" if first else " hidden"),
         '  <div class="ood2 ood2--%d">' % len(clips)]

    # A header only where the columns mean different things. The three
    # SkillWeaver clips are interchangeable samples, so numbering them in the
    # cells is all the label they need.
    if len(clips) == 2:
        L.append('    <div class="ood2-head" aria-hidden="true">')
        L.append('      <div></div>')
        for c in clips:
            L.append('      <span class="ood2-head__name">%s</span>' % c)
        L.append('    </div>')

    for t in range(1, TASKS + 1):
        L.append('    <div class="ood2-row">')
        L.append('      <div class="ood2-row__task">')
        L.append('        <p class="ood2-row__name">Task %d name</p>' % t)
        if renamed:
            L.append('        <p class="ood2-row__note">&rarr; perturbed task '
                     'name</p>')
        L.append('      </div>')
        for c in clips:
            L += cell(c, 3)
        L.append('    </div>')
    L += ['  </div>', '</div>']
    return L


def build():
    L = ['<div class="tabs" role="tablist" aria-label="LIBERO suite" data-tabs>']
    for i, (s, name) in enumerate(SUITES):
        L.append('  <button class="tab" role="tab" id="tab-ood-%s" '
                 'aria-controls="panel-ood-%s" aria-selected="%s">%s</button>'
                 % (s, s, "true" if i == 0 else "false", name))
    L.append('</div>')

    for i, (s, name) in enumerate(SUITES):
        L.append('')
        L.append('<div class="panel" id="panel-ood-%s" role="tabpanel" '
                 'aria-labelledby="tab-ood-%s"%s>'
                 % (s, s, "" if i == 0 else " hidden"))
        L.append('  <div class="tabs tabs--sub" role="tablist" '
                 'aria-label="%s clips" data-tabs>' % name)
        for j, (k, vlabel, _, _) in enumerate(VIEWS):
            L.append('    <button class="tab" role="tab" id="tab-ood-%s-%s" '
                     'aria-controls="panel-ood-%s-%s" aria-selected="%s">%s'
                     '</button>'
                     % (s, k, s, k, "true" if j == 0 else "false", vlabel))
        L.append('  </div>')
        for j, (k, vlabel, clips, renamed) in enumerate(VIEWS):
            for line in view_panel(s, k, vlabel, clips, renamed, j == 0):
                L.append("  " + line)
        L.append('</div>')

    return "\n".join("      " + x if x else "" for x in L)


def main():
    html = open(HTML, encoding="utf-8").read()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html):
        sys.exit("markers not found in index.html -- insert them first")
    open(HTML, "w", encoding="utf-8").write(
        pat.sub(lambda _: "%s\n%s\n%s" % (BEGIN, build(), END), html))

    per = sum(len(c) for _, _, c, _ in VIEWS) * TASKS
    print("%d suites x %d views, %d clips each -> %d placeholders"
          % (len(SUITES), len(VIEWS), per, per * len(SUITES)))
    for k, label, clips, renamed in VIEWS:
        print("  %-22s %d rows x %d clips%s"
              % (label, TASKS, len(clips), "  (rows name a new task)" if renamed else ""))


if __name__ == "__main__":
    main()
