#!/usr/bin/env python3
"""Generate the Memory-vs-no-Memory panel of the Ablations section.

One wide animation of the memory loop, over tab:memory-ablation from the paper:

  PAST SEARCH --distill--> MEMORY LIBRARY --retrieve top-k--> NEW SEARCH

  Generation  a past search (fork into a lying mug) fails; the failure is traced
              back to its earliest cause, the trajectory is distilled by a VLM,
              and a new entry lands in the library (app:memory_module).
  Retrieval   a new task (toothbrush into a lying cup) arrives; the selector VLM
              pulls the top-2 entries into the agent's context, and the search
              sets the cup upright before inserting -- the prerequisite the
              paper credits for Toothbrush -> Lying Cup going from 0% to 80%.

The library entries are verbatim keys from tab:memory_examples, their one-line
summaries shortened from the entries. Pairing that particular entry with that
past search is illustrative: both tasks come from the paper's task lists, but
the paper does not say which search produced which entry.

Same visual language and element model as the other two ablation animations
(tools/make_search_ablation.py, tools/make_verifier_ablation.py).

    python3 tools/make_memory_ablation.py [--frames DIR]
"""
import argparse
import io
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import chartlib  # noqa: E402
import make_search_ablation as sa  # noqa: E402
import make_verifier_ablation as va  # noqa: E402  (Clock, edge, node, token, glow, goal, css_for)

ROOT = Path(__file__).resolve().parent.parent
DEF_HTML = ROOT / "index.html"
DEF_CSS = ROOT / "css" / "style.css"
TEX = va.TEX

BEGIN_H = "<!-- >>> MEMORY ABLATION — generated by tools/make_memory_ablation.py, do not edit by hand >>> -->"
END_H = "<!-- <<< MEMORY ABLATION <<< -->"
BEGIN_C = "/* >>> MEMORY ABLATION — generated by tools/make_memory_ablation.py, do not edit by hand >>> */"
END_C = "/* <<< MEMORY ABLATION <<< */"

SPACE, SW_LINE, LABEL = sa.SPACE, sa.SW_LINE, sa.LABEL
NODE_FILL, NODE_STROKE = sa.NODE_FILL, sa.NODE_STROKE
TEAL, INDIGO, AMBER, ROSE = sa.TEAL, sa.INDIGO, sa.AMBER, sa.ROSE
MONO, R, f = sa.MONO, sa.R, sa.f
TEXT = "#D7DCE5"                       # primary text on the space panel

VB_W, VB_H = 1090, 300
EXEC, VERDICT = 0.8, 0.6

# Library: newest entry lands in the top slot.
CARD_X, CARD_W, CARD_H = 430, 300, 40
SLOTS = [44, 92, 140, 188, 236]
NEW = ("prepare container before insertion", "lying cup or mug: set it upright before inserting")
OLD = [("place beside target", "&#8220;beside&#8221; = the vacant spot next to it, not on it"),
       ("align elongated object for insertion", "long axis along the container's vertical axis"),
       ("straighten up objects", "upright axis to world vertical, back in its place"),
       ("place into side-opening container", "approach from the side; a top-down place collides")]
RETRIEVED = [0, 2]                     # slots the selector pulls: the new entry, and "align elongated ..."

# Past search (left) and new search (right).
P_ROOT, P_N1, P_N2 = (45, 150), (135, 150), (225, 150)
DISTILL = (280, 130, 100, 40)          # x, y, w, h
RETRIEVE = (780, 92, 150, 40)
N_X = [795, 860, 925, 990, 1055]
N_Y = 215
N_STEPS = ["pick cup", "upright", "pick brush", "insert"]


def text(x, y, s, size=10, fill=LABEL, anchor="start", weight=None, spacing=None):
    w = f' font-weight="{weight}"' if weight else ""
    ls = f' letter-spacing="{spacing}"' if spacing else ""
    return (f'<text x="{f(x)}" y="{f(y)}" text-anchor="{anchor}" font-family="{MONO}" font-size="{size}"'
            f'{w}{ls} fill="{fill}">{s}</text>')


def title(x, y, s, anchor="start"):
    return text(x, y, s, 10, LABEL, anchor, spacing=1.5)


def box(x, y, w, h, stroke=SW_LINE, fill=NODE_FILL, width=1.4, dash=None):
    da = f' stroke-dasharray="{dash}"' if dash else ""
    return (f'<rect x="{f(x)}" y="{f(y)}" width="{f(w)}" height="{f(h)}" rx="8" fill="{fill}" '
            f'stroke="{stroke}" stroke-width="{width}"{da}/>')


def start(xy):
    x, y = xy
    return (f'<circle cx="{x}" cy="{y}" r="{R}" fill="{NODE_FILL}" stroke="{NODE_STROKE}" stroke-width="1.6"/>'
            + sa.label(x, y + 22, "START"))


def card_body(y, key, line):
    return (text(CARD_X + 12, y + 17, key, 11, TEXT, weight=700)
            + text(CARD_X + 12, y + 31, line, 9.5, LABEL))


def flow(ck, uid, d, L, t_arrive, color, dur=0.6):
    """A dash running along a guide path, arriving at t_arrive."""
    t0 = t_arrive - dur
    return (sa.El(uid, "path", {"d": d, "fill": "none", "stroke": color, "stroke-width": "3",
                                "stroke-linecap": "round"}, dash=f"16 {f(L + 32)}")
            .track("o", [(0.0, 0.0), (t0, 0.0), (t0 + 0.03, 1.0), (t_arrive, 1.0), (t_arrive + 0.06, 0.0),
                         (ck.cycle, 0.0)])
            .track("d", [(0.0, 16.0), (t0, 16.0), (t_arrive, -(L - 16)), (ck.cycle, -(L - 16))]))


def curve(p, q):
    """Horizontal-tangent cubic from p to q, with its length."""
    (x1, y1), (x2, y2) = p, q
    cx = (x1 + x2) / 2
    pts = sa.cubic_pts(p, (cx, y1), (cx, y2), q)
    return f"M{f(x1)},{f(y1)} C{f(cx)},{f(y1)} {f(cx)},{f(y2)} {f(x2)},{f(y2)}", sa.plen(pts)


def guide(d):
    return (f'<path d="{d}" fill="none" stroke="{SW_LINE}" stroke-width="1.3" stroke-dasharray="3 4" '
            f'stroke-linecap="round"/>')


def build():
    P = "ma"
    # ---- timeline ----------------------------------------------------------
    t_instr_a = 0.4
    t_n1, t_n2 = 0.7, 0.7 + EXEC + 0.2                 # edges start growing
    v_n1, v_n2 = t_n1 + VERDICT, t_n2 + VERDICT
    t_trace = v_n2 + 0.9                               # rose trace arrives back at the root
    t_cause = t_trace + 0.1
    t_distill = t_cause + 1.0                          # flow into the distill box arrives
    t_card = t_distill + 1.1                           # new entry lands
    t_instr_b = t_card + 1.2
    t_pick = t_instr_b + 0.9                           # selector marks the top-2
    t_ctx = t_pick + 0.9                               # entries arrive in the agent context
    t_root = t_ctx + 0.7
    steps = [t_root + 0.25 + k * (EXEC + 0.05) for k in range(4)]
    t_glow = steps[-1] + VERDICT + 0.3
    ck = va.Clock(t_glow + 4.6)

    els = [sa.gradient("maWin", N_X[0], N_X[-1])]

    # ---- static scaffold (visible throughout, so a paused frame still reads) ---
    dx, dy, dw, dh = DISTILL
    rx, ry, rw, rh = RETRIEVE
    d_in = f"M{P_N2[0] + R},{P_N2[1]} L{dx},{dy + dh / 2}"
    L_in = dx - (P_N2[0] + R)
    d_out, L_out = curve((dx + dw, dy + dh / 2), (CARD_X, SLOTS[0] + CARD_H / 2))
    d_ret = [curve((CARD_X + CARD_W, SLOTS[s] + CARD_H / 2), (rx, ry + rh / 2)) for s in RETRIEVED]
    d_ctx = f"M{rx + 22},{ry + rh} L{N_X[0]},{N_Y - R}"
    L_ctx = ((N_X[0] - rx - 22) ** 2 + (N_Y - R - ry - rh) ** 2) ** 0.5
    static = [title(30, 26, "PAST SEARCH"), title(CARD_X + CARD_W / 2, 26, "MEMORY LIBRARY", "middle"),
              title(780, 26, "NEW SEARCH"),
              guide(d_in), guide(d_out), guide(d_ctx)] + [guide(d) for d, _ in d_ret] + [
              box(dx, dy, dw, dh), text(dx + dw / 2, dy + 17, "DISTILL", 10.5, TEXT, "middle", 700, 1),
              text(dx + dw / 2, dy + 31, "VLM", 9, LABEL, "middle"),
              box(rx, ry, rw, rh), text(rx + rw / 2, ry + 17, "RETRIEVE TOP-2", 10.5, TEXT, "middle", 700, 1),
              text(rx + rw / 2, ry + 31, "selector VLM", 9, LABEL, "middle"),
              box(CARD_X, SLOTS[0], CARD_W, CARD_H, fill="none", width=1.1, dash="3 4")]
    for (key, line), y in zip(OLD, SLOTS[1:]):
        static += [box(CARD_X, y, CARD_W, CARD_H), card_body(y, key, line)]
    els += static

    # ---- generation: the past search fails -----------------------------------
    els.append(sa.El(f"{P}-instr-a", "g", children=[
        text(30, 52, "&#8220;put the fork in the lying mug&#8221;", 11, TEXT)]).track("o", ck.appear(t_instr_a)))
    els.append(va.edge(ck, f"{P}-e1", P_ROOT, P_N1, t_n1, v_n1))
    els.append(va.edge(ck, f"{P}-e2", P_N1, P_N2, t_n2, v_n2))
    els.append(start(P_ROOT))
    els.append(va.node(ck, f"{P}-n1", *P_N1, "ok", t_n1 + 0.3, v_n1))
    els.append(va.node(ck, f"{P}-n2", *P_N2, "fail", t_n2 + 0.3, v_n2))
    els.append(sa.El(f"{P}-lab-a", "g", children=[
        sa.label(P_N1[0], P_N1[1] + 22, "pick fork"), sa.label(P_N2[0], P_N2[1] + 22, "insert")])
        .track("o", ck.appear(t_n1 + 0.3)))
    # traced back to its earliest cause: the first decision never set the mug upright
    d_tr, L_tr = sa.chain_path([P_ROOT, P_N1, P_N2])
    els.append(sa.El(f"{P}-trace", "path", {"d": d_tr, "fill": "none", "stroke": ROSE, "stroke-width": "3",
                                             "stroke-linecap": "round"}, dash=f"16 {f(L_tr + 32)}")
               .track("o", [(0.0, 0.0), (t_trace - 0.6, 0.0), (t_trace - 0.57, 1.0), (t_trace, 1.0),
                            (t_trace + 0.06, 0.0), (ck.cycle, 0.0)])
               .track("d", [(0.0, -(L_tr - 16)), (t_trace - 0.6, -(L_tr - 16)), (t_trace, 16.0), (ck.cycle, 16.0)]))
    els.append(sa.El(f"{P}-cause", "g", children=[
        f'<circle cx="{P_ROOT[0]}" cy="{P_ROOT[1]}" r="13" fill="none" stroke="{ROSE}" stroke-width="1.6" '
        f'stroke-dasharray="3 3"/>',
        text(30, 208, "earliest cause: the mug was", 9.5, ROSE),
        text(30, 222, "never set upright", 9.5, ROSE)]).track("o", ck.appear(t_cause, dur=0.3)))

    # ---- generation: distilled into a new entry -----------------------------
    els.append(flow(ck, f"{P}-to-distill", d_in, L_in, t_distill, AMBER, dur=0.4))
    els.append(sa.El(f"{P}-distill-hi", "g", children=[box(dx, dy, dw, dh, stroke=AMBER, fill="none", width=1.8)])
               .track("o", ck.window(t_distill, t_card + 0.2)))
    els.append(flow(ck, f"{P}-to-lib", d_out, L_out, t_card - 0.05, AMBER, dur=0.6))
    y0 = SLOTS[0]
    card_rect = (sa.El(f"{P}-card-rect", "rect", {"x": CARD_X, "y": y0, "width": CARD_W, "height": CARD_H,
                                                  "rx": "8", "fill": NODE_FILL, "stroke": AMBER, "stroke-width": "1.6"})
                 .track("c", [(0.0, AMBER), (t_card + 1.0, AMBER), (t_card + 1.6, SW_LINE), (ck.cycle, SW_LINE)]))
    els.append(sa.El(f"{P}-card", "g", children=[card_rect, card_body(y0, *NEW)],
                     origin=(CARD_X + CARD_W / 2, y0 + CARD_H / 2))
               .track("o", ck.appear(t_card)).track("s", ck.pop(t_card, lo=0.85)))

    # ---- retrieval: a new task pulls the top-2 into context ------------------
    els.append(sa.El(f"{P}-instr-b", "g", children=[
        text(780, 52, "&#8220;put the toothbrush in the lying cup&#8221;", 11, TEXT)])
        .track("o", ck.appear(t_instr_b)))
    for k, s in enumerate(RETRIEVED):
        y = SLOTS[s]
        els.append(sa.El(f"{P}-pick-{k}", "g", children=[
            box(CARD_X - 3, y - 3, CARD_W + 6, CARD_H + 6, stroke=AMBER, fill="none", width=1.8)])
            .track("o", ck.appear(t_pick + 0.15 * k)))
        d, L = d_ret[k]
        els.append(flow(ck, f"{P}-to-ctx-{k}", d, L, t_ctx, AMBER, dur=0.6))
    els.append(sa.El(f"{P}-retrieve-hi", "g", children=[box(rx, ry, rw, rh, stroke=AMBER, fill="none", width=1.8)])
               .track("o", ck.appear(t_ctx)))
    els.append(flow(ck, f"{P}-to-plan", d_ctx, L_ctx, t_root, INDIGO, dur=0.45))

    # ---- retrieval: the new search sets the cup upright first ----------------
    els.append(sa.El(f"{P}-root-b", "g", children=[start((N_X[0], N_Y))]).track("o", ck.appear(t_root)))
    pts = [(x, N_Y) for x in N_X]
    for k, t in enumerate(steps):
        els.append(va.edge(ck, f"{P}-f{k}", pts[k], pts[k + 1], t, t + VERDICT))
        els.append(va.node(ck, f"{P}-m{k}", *pts[k + 1], "ok", t + 0.3, t + VERDICT))
        els.append(sa.El(f"{P}-ml{k}", "g", children=[sa.label(pts[k + 1][0], N_Y + 22, N_STEPS[k])])
                   .track("o", ck.appear(t + 0.3)))
    els.append(va.glow(ck, f"{P}-glow", pts, t_glow, "maWin"))
    els.append(va.goal(ck, f"{P}-goal", *pts[-1], t_glow + 1.0))
    return ck, els


# ----------------------------------------------------------------------------
# Paper table
# ----------------------------------------------------------------------------
def parse_tex():
    t = TEX.read_text(encoding="utf-8")
    i = t.index(r"\label{tab:memory-ablation}")
    blk = t[t.rindex(r"\begin{tabular}", 0, i):i]
    head = re.search(r"Method(.*?)\\\\", blk, re.S).group(1)
    cols = [re.sub(r"\s+", " ", c.replace(r"$\rightarrow$", "&rarr;")).strip() for c in head.split("&") if c.strip()]
    unbest = lambda c: re.sub(r"\\best\{([^}]*)\}", r"\1", c).strip()
    rows = [(m.group(1).strip(), [unbest(c) for c in m.group(2).split("&")])
            for m in re.finditer(r"\n\s*(w/o? Memory)\s*&([^\n]*?)\\\\", blk)]
    if len(rows) != 2 or any(len(v) != len(cols) for _, v in rows):
        sys.exit("unexpected shape in tab:memory-ablation")
    return cols, rows


def chart(cols, rows):
    """tab:memory-ablation as grouped bars: one pair per task, average last."""
    wo, w = dict(rows)["w/o Memory"], dict(rows)["w/ Memory"]
    svg = chartlib.grouped_bars(
        name="memAbl", gradient="memAblBar",
        groups=[c.replace("&rarr;", "&rarr;\u200b") for c in cols],
        series=[{"label": name, "cls": "bar--gt" if name == "w/o Memory" else "bar--ours",
                 "values": [float(v) for v in vals]} for name, vals in rows],
        ylab="MCTS success rate (%)", atitle="Task", ymax=108,
        grid=(0, 25, 50, 75, 100), fmt="%.1f", vb_w=660, bar_w=34,
        title="Search success with and without experience memory",
        desc="MCTS success rate per task: " + "; ".join(
            "%s %s" % (n, ", ".join("%s %s%%" % (c, v) for c, v in zip(cols, vals)))
            for n, vals in rows) + ".")
    return (['<figure class="figure">',
             '  <div class="chart-wrap chart-wrap--sm" role="region" tabindex="0" aria-label="Search success with and without '
             'memory">']
            + [svg] + ['  </div>', '</figure>',
             '<p class="table-note">MCTS success rate (%) over ten searches per task at maximum depth <i>K</i> = 6, on '
             'tasks that hinge on orientation adjustment, spatial reasoning, or an implicit prerequisite. <b>Memory '
             f'lifts average search success from {wo[-1]}% to {w[-1]}%.</b></p>'])


# ----------------------------------------------------------------------------
# Rendering
# ----------------------------------------------------------------------------
ARIA = ("Experience memory. Generation: a past search, putting a fork in a lying mug, fails; the failure is traced "
        "back to its earliest cause, the mug never being set upright, and a VLM distills the trajectory into a new "
        "library entry, prepare container before insertion. Retrieval: a new task, putting a toothbrush in a lying "
        "cup, arrives; a selector VLM retrieves the top two entries into the agent's context, and the search picks "
        "the cup, sets it upright, picks the toothbrush and inserts it.")


def html_block(ck, els, cols, rows):
    return "\n".join([
        BEGIN_H,
        '<figure class="abl-anim mem-anim">',
        '  <figcaption class="abl-anim__cap"><b>Experience memory</b><span>distilled after a search &middot; '
        'retrieved before the next</span></figcaption>',
        f'<svg class="search-anim" viewBox="0 0 {VB_W} {VB_H}" role="img" aria-label="{ARIA}">',
        "\n".join(sa.render(e, "page") for e in els),
        '</svg>',
        '</figure>'] + chart(cols, rows) + [END_H]).replace('class="sa', 'class="va')


def css_block(ck, els):
    static = f"""{BEGIN_C}
.mem-anim .va {{
  animation-duration: {f(ck.cycle)}s;
  animation-timing-function: linear;
  animation-iteration-count: infinite;
  animation-fill-mode: both;
}}

.mem-anim .va-glow {{
  filter: drop-shadow(0 0 7px rgba(255, 176, 32, 0.4));
}}

.mem-anim .va-goal {{
  filter: drop-shadow(0 0 8px rgba(255, 176, 32, 0.55));
}}

.mem-table {{
  margin-top: 22px;
}}
"""
    rules = "\n".join(va.css_for(x, ck) for x in sa.walk(els))
    tail = f"""
/* Without motion: rests at the HOLD state, both searches finished. */
@media (prefers-reduced-motion: reduce) {{
  .mem-anim .va {{
    animation: none !important;
  }}
}}
{END_C}"""
    return static + "\n" + rules + "\n" + tail


def patch_html(path, block):
    h = path.read_text()
    p0 = h.index('id="panel-abl-memory"')
    p1 = h.find("<!--\n", p0)
    ind = "        "
    new = "\n".join((ind + ln) if ln.strip() else ln for ln in block.split("\n"))
    if BEGIN_H in h[p0:p1]:
        a = h.index(BEGIN_H, p0)
        b = h.index(END_H, a) + len(END_H)
    else:
        a = h.index('<div class="media media--placeholder">', p0)
        assert a < p1, "placeholder not inside #panel-abl-memory"
        b = h.index("</div>", h.index("placeholder__text", a)) + len("</div>")
    a = h.rindex("\n", 0, a) + 1
    path.write_text(h[:a] + new + h[b:])


def frames(outdir, ck, els, n=10):
    import cairosvg
    from PIL import Image, ImageDraw
    tiles = []
    for i in range(n):
        t = ck.cycle * (i + 0.5) / n if i < n - 1 else ck.hold
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VB_W} {VB_H}" width="{VB_W}" height="{VB_H}">'
               f'<rect width="100%" height="100%" fill="{SPACE}"/>' + "".join(sa.render(e, "frame", t) for e in els)
               + "</svg>")
        img = Image.open(io.BytesIO(cairosvg.svg2png(bytestring=svg.encode()))).convert("RGB")
        tile = Image.new("RGB", (VB_W, VB_H + 18), "white")
        ImageDraw.Draw(tile).text((6, 3), f"t = {t:.1f} / {ck.cycle:.1f} s", fill=(20, 20, 20))
        tile.paste(img, (0, 18))
        tiles.append(tile)
    cols, gap = 2, 12
    rows = (len(tiles) + cols - 1) // cols
    tw, th = tiles[0].size
    sheet = Image.new("RGB", (cols * tw + (cols - 1) * gap, rows * th + (rows - 1) * gap), (150, 156, 166))
    for i, tile in enumerate(tiles):
        sheet.paste(tile, ((i % cols) * (tw + gap), (i // cols) * (th + gap)))
    outdir.mkdir(parents=True, exist_ok=True)
    p = outdir / "memory_ablation_frames.png"
    sheet.save(p)
    return p


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--html", type=Path, default=DEF_HTML)
    ap.add_argument("--css", type=Path, default=DEF_CSS)
    ap.add_argument("--frames", type=Path)
    args = ap.parse_args()
    cols, rows = parse_tex()
    ck, els = build()
    ids = [x.uid for x in sa.walk(els)]
    assert len(ids) == len(set(ids)), "duplicate element ids"
    patch_html(args.html, html_block(ck, els, cols, rows))
    cb = css_block(ck, els)
    c = args.css.read_text()
    if BEGIN_C in c:
        a, b = c.index(BEGIN_C), c.index(END_C) + len(END_C)
        c = c[:a] + cb + c[b:]
    else:
        c = c.rstrip("\n") + "\n\n" + cb + "\n"
    args.css.write_text(c)
    print(f"cycle {ck.cycle:.1f}s, {len(ids)} animated elements, css block {len(cb) / 1024:.1f} KB")
    if args.frames:
        print("frames:", frames(args.frames, ck, els))


if __name__ == "__main__":
    main()
