#!/usr/bin/env python3
"""Generate the grouped bar chart for the pairwise LIBERO-PRO results.

The point of this table is an extreme contrast, not a fine comparison: the
baseline is at or near zero on five of the ten augmentation pairs, ours is
34-83. A reader should see that without doing ten subtractions, so the numbers
are drawn as bars and the table below carries the exact values.

The data is parsed from the paper source, not retyped, so the page cannot drift
from `tab:libero-pro-pairs`. Re-run after the numbers change:

    python3 tools/make_pairs_chart.py

The ten pairs are drawn as two rows of five rather than one row of ten, so
each group is wide enough to carry its combination spelled out -- "Language +
Object" rather than "L+O", which otherwise sends the reader back to a legend
for every bar they look at.

It rewrites the marked block in index.html in place. Colors and type live in
css/style.css under `.chart` -- only geometry is generated here.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "index.html")
TEX = os.path.expanduser(
    "~/corl_2026/6a04a8918ed80a6693230556/sec/exps_katef.tex")

BEGIN = "      <!-- >>> PAIRS CHART: generated by tools/make_pairs_chart.py >>> -->"
END = "      <!-- <<< PAIRS CHART <<< -->"

# What the single letters in the paper's column heads stand for.
AXIS = {"L": "Language", "O": "Object", "P": "Position",
        "T": "Task", "E": "Environment"}

# Geometry, in viewBox units.
VB_W = 1166
PAD_L, PAD_R = 62, 14
PER_ROW = 5
GRID = (0, 25, 50, 75, 100)
BAR_W, BAR_GAP = 62, 12

RISE = 0.62       # one bar's climb
HOLD = 0.18       # a beat between the two, so they read as two acts

PLOT_H = 230      # one row's plot area, baseline to 100%
TOP = 46          # first row's 100% line, leaving the legend its own air
XLAB_DY = 26      # baseline to the combination name under it
ROW_GAP = 54      # name to the next row's 100% line

X0, X1 = PAD_L, VB_W - PAD_R
ROW_PITCH = PLOT_H + XLAB_DY + ROW_GAP
VB_H = TOP + 2 * ROW_PITCH - ROW_GAP + 16


def parse_tex():
    """Pull the two stacked column blocks out of tab:libero-pro-pairs."""
    t = open(TEX, encoding="utf-8").read()
    i = t.index(r"\label{tab:libero-pro-pairs}")
    b = t[max(0, i - 4000):i]
    b = b[b.rindex(r"\begin{tabular}"):]

    def clean(x):
        x = re.sub(r"\\begin\{tabular\}\{[^}]*\}", "", x)
        for k in (r"\toprule", r"\midrule", r"\bottomrule", r"\end{tabular}"):
            x = x.replace(k, "")
        return x.replace("~", " ").strip()

    heads, rows = [], []
    for raw in b.split(r"\\"):
        raw = re.sub(r"(?<!\\)%.*$", "", raw, flags=re.M)
        if "&" not in raw:
            continue
        cells = []
        for cp in raw.split("&"):
            txt = re.sub(r"\\best\{([^}]*)\}", r"\1", cp)
            txt = re.sub(r"\\(up|dn)\{[^}]*\}", "", txt)
            cells.append(clean(txt))
        (heads if cells[0] == "Method" else rows).append(cells)

    if len(heads) != 2 or len(rows) != 4:
        sys.exit("unexpected table shape: %d headers, %d rows"
                 % (len(heads), len(rows)))
    cols = heads[0][1:] + heads[1][1:]
    gt = [float(v) for v in rows[0][1:] + rows[2][1:]]
    ours = [float(v) for v in rows[1][1:] + rows[3][1:]]
    if not len(cols) == len(gt) == len(ours) == 10:
        sys.exit("expected 10 pairs, got %d" % len(cols))
    return cols, gt, ours


def spell(code):
    """`L+O` -> `Language + Object`."""
    return " + ".join(AXIS[c] for c in code.split("+"))


def base(row):
    return TOP + row * ROW_PITCH + PLOT_H       # the row's zero baseline


def y_of(v, row):
    return base(row) - v / 100.0 * PLOT_H


# Every baseline climbs at once, then every one of ours climbs over the top of
# them: two readings of the same chart rather than twenty separate events.
D_GT = 0.0
D_OURS = RISE + HOLD


def bar(x, v, row, cls, d):
    """One bar plus its value label. A zero bar is a label and nothing else,
    which is the honest drawing of a zero and reads as a result, not a gap."""
    top = y_of(v, row)
    out = []
    if v > 0:
        h = base(row) - top
        out.append('<rect class="bar rise %s" x="%g" y="%.1f" width="%d" '
                   'height="%.1f" rx="%.1f" style="--d:%.2fs" />'
                   % (cls, x, top, BAR_W, h, min(3, h / 2), d))
    # The number lands as its bar settles, not before it has anything to label.
    out.append('<text class="val pop %s" x="%.1f" y="%.1f" style="--d:%.2fs">'
               '%.1f</text>'
               % (cls.replace("bar--", "val--"), x + BAR_W / 2, top - 8,
                  d + RISE * 0.7, v))
    return out


def build(cols, gt, ours):
    rows = (len(cols) + PER_ROW - 1) // PER_ROW
    group_w = (X1 - X0) / PER_ROW
    pair_w = 2 * BAR_W + BAR_GAP
    L = ['<svg class="chart chart--play chart--pairs" viewBox="0 0 %d %d" role="img" '
         'aria-labelledby="pairsChartTitle pairsChartDesc">' % (VB_W, VB_H),
         '  <title id="pairsChartTitle">Success rate under pairwise '
         'augmentation</title>',
         '  <desc id="pairsChartDesc">Grouped bars over ten augmentation '
         'pairs, five per row. Training on ground-truth data alone collapses '
         'to zero on three of them and stays under 21 percent on five more; '
         'adding SkillWeaver data reaches 34 to 83 percent.</desc>',
         '  <defs>',
         '    <linearGradient id="pairsBar" gradientUnits="userSpaceOnUse" '
         'x1="%d" y1="0" x2="%d" y2="0">' % (X0, X1),
         '      <stop class="g-a" offset="0" />',
         '      <stop class="g-b" offset="1" />',
         '    </linearGradient>',
         '  </defs>']

    # Legend once, above everything, rather than repeated per row.
    L.append('  <g class="legend">')
    for x, cls, label in ((X0, "bar--gt", "GT only"),
                          (X0 + 150, "bar--ours", "SkillWeaver Data + GT")):
        L.append('    <rect class="bar %s" x="%d" y="12" width="13" '
                 'height="13" rx="3" />' % (cls, x))
        L.append('    <text class="key" x="%d" y="23">%s</text>'
                 % (x + 20, label))
    L.append('  </g>')

    for r in range(rows):
        L.append('  <g class="row">')
        L.append('    <g class="grid">')
        for v in GRID:
            y = y_of(v, r)
            L.append('      <line class="%s" x1="%d" y1="%.1f" x2="%d" '
                     'y2="%.1f" />'
                     % ("axis" if v == 0 else "rule", X0, y, X1, y))
            L.append('      <text class="tick" x="%d" y="%.1f">%d</text>'
                     % (X0 - 12, y + 4, v))
        L.append('    </g>')
        L.append('    <text class="ylab" transform="translate(16 %.1f) '
                 'rotate(-90)">Success rate (%%)</text>'
                 % (y_of(50, r)))

        L.append('    <g class="bars">')
        for j in range(PER_ROW):
            i = r * PER_ROW + j
            if i >= len(cols):
                break
            gx = X0 + j * group_w
            bx = gx + (group_w - pair_w) / 2
            L.append('      <g>')
            for s_ in bar(bx, gt[i], r, "bar--gt", D_GT):
                L.append("        " + s_)
            for s_ in bar(bx + BAR_W + BAR_GAP, ours[i], r, "bar--ours",
                          D_OURS):
                L.append("        " + s_)
            L.append('        <text class="xlab" x="%.1f" y="%.1f">%s</text>'
                     % (gx + group_w / 2, base(r) + XLAB_DY, spell(cols[i])))
            L.append('      </g>')
        L.append('    </g>')
        L.append('  </g>')

    L.append('</svg>')
    return "\n".join("      " + s_ for s_ in L)


def main():
    cols, gt, ours = parse_tex()
    svg = build(cols, gt, ours)

    html = open(HTML, encoding="utf-8").read()
    block = "%s\n%s\n%s" % (BEGIN, svg, END)
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html):
        sys.exit("markers not found in index.html -- insert them first")
    open(HTML, "w", encoding="utf-8").write(pat.sub(lambda _: block, html))

    print("chart: %d pairs" % len(cols))
    for n, a, b in zip(cols, gt, ours):
        print("  %-4s %5.1f -> %5.1f  %+.1f" % (n, a, b, b - a))


if __name__ == "__main__":
    main()
