#!/usr/bin/env python3
"""Generate the data-scaling curve, drawn in the page's own hand and animated.

The paper prints this as a matplotlib PNG (figure/libero_scaling_object.png,
fig:libero-pro-scaling). On the page it is native SVG instead, sharing the
`.chart` type with the two bar charts beside it -- and running the full
teal-indigo-amber spectrum rather than their two stops, so the payoff point at
100% lands on the warm end -- so
the three read as one family rather than as a screenshot dropped into a layout.

It builds one point at a time from the 3.125% fraction. The line is revealed by
a travelling dash and each marker pops as the line reaches it -- which only
lines up if the marker delays are measured along the path, not spread evenly:
the segments differ in length because the curve is steep in the middle. Hence
CUM below.

Numbers come from the figure's own plotting script, transcribed once:

    /data/user_data/hez2/corl_build/plot_fig3_scaling.py

Re-run after they change:

    python3 tools/make_scaling_chart.py
"""

import math
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "index.html")

BEGIN = "        <!-- >>> SCALING CHART: generated by tools/make_scaling_chart.py >>> -->"
END = "        <!-- <<< SCALING CHART <<< -->"

FRACTION = ["3.125%", "6.25%", "12.5%", "25%", "50%", "100%"]
DEMOS = [21, 44, 89, 180, 384, 708]
SUCCESS = [13.1, 21.2, 35.7, 55.8, 61.9, 67.6]
GT_ONLY = 19.6

BUILD = 3.4          # seconds for the line to travel end to end
POP = 0.42           # a marker's own pop, running past its delay

VB_W, VB_H = 640, 380
X0, X1 = 62, 622
Y_TOP, Y_BOT = 62, 318
Y_MAX = 80
INSET = 24           # keeps the end markers and their labels off the frame
TICKS = (0, 20, 40, 60, 80)


def y_of(v):
    return Y_BOT - v / float(Y_MAX) * (Y_BOT - Y_TOP)


def xs():
    span = (X1 - X0) - 2 * INSET
    return [X0 + INSET + i * span / (len(DEMOS) - 1.0)
            for i in range(len(DEMOS))]


def build():
    px = xs()
    py = [y_of(v) for v in SUCCESS]
    pts = list(zip(px, py))

    seg = [math.hypot(b[0] - a[0], b[1] - a[1]) for a, b in zip(pts, pts[1:])]
    total = sum(seg)
    cum = [0.0]
    for s in seg:
        cum.append(cum[-1] + s)
    delay = [c / total * BUILD for c in cum]

    L = ['<svg class="chart chart--sm chart--play" viewBox="0 0 %d %d" '
         'role="img" aria-labelledby="scalingTitle scalingDesc">' % (VB_W, VB_H),
         '  <title id="scalingTitle">OOD success rate against amount of '
         'generated data</title>',
         '  <desc id="scalingDesc">Average success rate on the LIBERO-PRO '
         'Object suite over the position, task and environment perturbations, '
         'rising from %s at %s of our data to %s at %s, against a %s '
         'ground-truth-only baseline.</desc>'
         % (SUCCESS[0], FRACTION[0], SUCCESS[-1], FRACTION[-1], GT_ONLY),
         '  <defs>',
         '    <linearGradient id="scalingLine" gradientUnits="userSpaceOnUse" '
         'x1="%.1f" y1="0" x2="%.1f" y2="0">' % (px[0], px[-1]),
         '      <stop class="g-a" offset="0" />',
         '      <stop class="g-b" offset="0.55" />',
         '      <stop class="g-c" offset="1" />',
         '    </linearGradient>',
         '  </defs>']

    L.append('  <g class="grid">')
    for v in TICKS:
        y = y_of(v)
        L += ['    <line class="%s" x1="%d" y1="%.1f" x2="%d" y2="%.1f" />'
              % ("axis" if v == 0 else "rule", X0, y, X1, y),
              '    <text class="tick" x="%d" y="%.1f">%d</text>'
              % (X0 - 10, y + 4, v)]
    L.append('  </g>')
    L.append('  <text class="ylab" transform="translate(20 %.1f) rotate(-90)">'
             'Average Success Rate (%%)</text>' % ((Y_TOP + Y_BOT) / 2))

    # Both axes are labelled, as in the paper: the fraction of our data on top,
    # what that is in demonstrations underneath.
    L.append('  <g class="axes">')
    L.append('    <text class="atitle" x="%.1f" y="20">Data Fraction</text>'
             % ((X0 + X1) / 2))
    for x, f in zip(px, FRACTION):
        L.append('    <text class="tick tick--mid" x="%.1f" y="42">%s</text>'
                 % (x, f))
    for x, d in zip(px, DEMOS):
        L.append('    <text class="tick tick--mid" x="%.1f" y="%d">%d</text>'
                 % (x, Y_BOT + 22, d))
    L.append('    <text class="atitle" x="%.1f" y="%d">Avg. Demos per '
             'Task</text>' % ((X0 + X1) / 2, Y_BOT + 48))
    L.append('  </g>')

    # The baseline this whole curve is measured against.
    gy = y_of(GT_ONLY)
    L += ['  <g class="ref pop" style="--d:0.12s">',
          '    <line class="gtline" x1="%d" y1="%.2f" x2="%d" y2="%.2f" />'
          % (X0, gy, X1, gy),
          '    <text class="key key--end" x="%d" y="%.2f">GT only: %s%%</text>'
          % (X1 - 4, gy - 8, GT_ONLY),
          '  </g>']

    d = " ".join(("M" if i == 0 else "L") + "%.2f %.2f" % p
                 for i, p in enumerate(pts))
    L.append('  <path class="curve draw" d="%s" style="--len:%.2f" />'
             % (d, total))

    L.append('  <g class="marks">')
    for i, (x, y) in enumerate(pts):
        # The first point sits below the baseline and hard against the axis;
        # its label goes underneath so it does not fight the dashed line.
        ly, cls = (y + 20, " val--under") if i == 0 else (y - 13, "")
        L += ['    <g class="pop" style="--d:%.2fs">' % delay[i],
              '      <circle class="dot" cx="%.2f" cy="%.2f" r="5.5" />'
              % (x, y),
              '      <text class="val val--ours%s" x="%.2f" y="%.2f">%s</text>'
              % (cls, x, ly, SUCCESS[i]),
              '    </g>']
    L.append('  </g>')
    L.append('</svg>')
    return "\n".join("        " + s for s in L), delay


def main():
    svg, delay = build()
    html = open(HTML, encoding="utf-8").read()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html):
        sys.exit("markers not found in index.html -- insert them first")
    open(HTML, "w", encoding="utf-8").write(
        pat.sub(lambda _: "%s\n%s\n%s" % (BEGIN, svg, END), html))

    print("build %.1fs, last marker lands at %.2fs" % (BUILD, delay[-1] + POP))
    for f, d, v, t in zip(FRACTION, DEMOS, SUCCESS, delay):
        print("  %-7s %3d demos  %5.1f%%   pops at %.2fs" % (f, d, v, t))


if __name__ == "__main__":
    main()
