#!/usr/bin/env python3
"""Generate the grouped bar chart for the four-suite LIBERO-PRO results.

Drawn as 2x2 small multiples -- one panel per suite, three perturbations
inside each -- because that is the shape of the data in `tab:libero-pro`, and
because the four panel titles then line up with the four suite buttons above
the video grid. Flattening it to twelve groups in a row would lose that.

The numbers are parsed from the paper source, not retyped, so the page cannot
drift from the table. Re-run after they change:

    python3 tools/make_suites_chart.py

It rewrites the marked block in index.html in place. Colors and type live in
css/style.css under `.chart` -- only geometry is generated here.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "index.html")
TEX = os.path.expanduser(
    "~/corl_2026/6a04a8918ed80a6693230556/sec/exps_katef.tex")

BEGIN = "      <!-- >>> SUITES CHART: generated by tools/make_suites_chart.py >>> -->"
END = "      <!-- <<< SUITES CHART <<< -->"

# The table heads them by the bare suite name; the page calls them what the
# benchmark and the tab strip above call them.
SUITE = {"Object": "LIBERO-Object", "Spatial": "LIBERO-Spatial",
         "Goal": "LIBERO-Goal", "10": "LIBERO-10"}
PERT = {"Pos.": "Position", "Task": "Task", "Env.": "Environment"}

VB_W = 1166
PAD_L, PAD_R = 58, 8          # inside a panel
COL_GAP, ROW_GAP = 56, 62     # between panels
RISE = 0.62       # one bar's climb
HOLD = 0.18       # a beat between the two, so they read as two acts

PLOT_H = 196
TOP = 58                      # first row's 100% line, under the legend
TITLE_DY = -14                # panel title, above its 100% line
XLAB_DY = 24
GRID = (0, 25, 50, 75, 100)
BAR_W, BAR_GAP = 46, 10

COLS, ROWS = 2, 2
PANEL_W = (VB_W - COL_GAP) / COLS
ROW_PITCH = PLOT_H + XLAB_DY + ROW_GAP
VB_H = TOP + ROWS * ROW_PITCH - ROW_GAP + 14


def parse_tex():
    """Pull suites, perturbations and both method rows out of tab:libero-pro."""
    t = open(TEX, encoding="utf-8").read()
    i = t.index(r"\label{tab:libero-pro}")
    b = t[max(0, i - 4000):i]
    b = b[b.rindex(r"\begin{tabular}"):]

    def clean(x):
        x = re.sub(r"\\begin\{tabular\}\{[^}]*\}", "", x)
        x = re.sub(r"\\multicolumn\{\d+\}\{[^}]*\}\{([^}]*)\}", r"\1", x)
        x = re.sub(r"\\cmidrule(?:\(lr\))?\{[^}]*\}", "", x)
        for k in (r"\toprule", r"\midrule", r"\bottomrule", r"\end{tabular}",
                  "%"):
            x = x.replace(k, "")
        x = x.replace("\\ ", " ")
        return x.replace("~", " ").strip()

    suites, perts, rows = [], [], []
    for raw in b.split(r"\\"):
        raw = re.sub(r"(?<!\\)%.*$", "", raw, flags=re.M)
        if "&" not in raw:
            continue
        cells = [clean(re.sub(r"\\(up|dn)\{[^}]*\}", "",
                              re.sub(r"\\best\{([^}]*)\}", r"\1", c)))
                 for c in raw.split("&")]
        head = cells[0]
        if not head:                       # the \multicolumn suite band
            suites = [c for c in cells[1:] if c]
        elif head == "Method":
            perts = cells[1:]
        else:
            rows.append((head, cells[1:]))

    if len(suites) != 4 or len(perts) != 12 or len(rows) != 2:
        sys.exit("unexpected shape: %d suites, %d cols, %d rows"
                 % (len(suites), len(perts), len(rows)))
    per = len(perts) // len(suites)
    panels = []
    for s, suite in enumerate(suites):
        sl = slice(s * per, (s + 1) * per)
        panels.append((SUITE.get(suite, suite),
                       [PERT.get(p, p) for p in perts[sl]],
                       [float(v) for v in rows[0][1][sl]],
                       [float(v) for v in rows[1][1][sl]]))
    return [r[0] for r in rows], panels


# Every baseline climbs at once, then every one of ours climbs over the top of
# them: two readings of the same chart rather than twenty-four separate events.
D_GT = 0.0
D_OURS = RISE + HOLD


def panel_box(p):
    """(x0, x1, baseline) of panel p's plot area."""
    c, r = p % COLS, p // COLS
    px = c * (PANEL_W + COL_GAP)
    return px + PAD_L, px + PANEL_W - PAD_R, TOP + r * ROW_PITCH + PLOT_H


def build(methods, panels):
    L = ['<svg class="chart chart--play chart--suites" viewBox="0 0 %d %d" role="img" '
         'aria-labelledby="suitesChartTitle suitesChartDesc">' % (VB_W, VB_H),
         '  <title id="suitesChartTitle">Success rate under single '
         'perturbations, by LIBERO-PRO suite</title>',
         '  <desc id="suitesChartDesc">Four panels, one per LIBERO-PRO suite, '
         'each comparing training on ground-truth data alone against adding '
         'SkillWeaver data under position, task and environment '
         'perturbations. Adding our data wins all twelve comparisons.</desc>',
         '  <defs>']
    for p in range(len(panels)):
        x0, x1, _ = panel_box(p)
        L += ['    <linearGradient id="suitesBar%d" '
              'gradientUnits="userSpaceOnUse" x1="%.1f" y1="0" x2="%.1f" '
              'y2="0">' % (p, x0, x1),
              '      <stop class="g-a" offset="0" />',
              '      <stop class="g-b" offset="1" />',
              '    </linearGradient>']
    L.append('  </defs>')

    L.append('  <g class="legend">')
    for x, cls, label in ((PAD_L, "bar--gt", methods[0]),
                          (PAD_L + 150, "bar--ours", "SkillWeaver Data + GT")):
        L += ['    <rect class="bar %s" x="%d" y="12" width="13" height="13" '
              'rx="3" />' % (cls, x),
              '    <text class="key" x="%d" y="23">%s</text>' % (x + 20, label)]
    L.append('  </g>')

    for p, (title, names, gt, ours) in enumerate(panels):
        x0, x1, base = panel_box(p)
        group_w = (x1 - x0) / len(names)
        pair_w = 2 * BAR_W + BAR_GAP
        L.append('  <g class="panel-g">')
        L.append('    <text class="plab" x="%.1f" y="%.1f">%s</text>'
                 % (x0, base - PLOT_H + TITLE_DY, title))
        L.append('    <g class="grid">')
        for v in GRID:
            y = base - v / 100.0 * PLOT_H
            L += ['      <line class="%s" x1="%.1f" y1="%.1f" x2="%.1f" '
                  'y2="%.1f" />' % ("axis" if v == 0 else "rule", x0, y, x1, y),
                  '      <text class="tick" x="%.1f" y="%.1f">%d</text>'
                  % (x0 - 10, y + 4, v)]
        L.append('    </g>')
        L.append('    <text class="ylab" transform="translate(%.1f %.1f) '
                 'rotate(-90)">Success rate (%%)</text>'
                 % (x0 - 44, base - PLOT_H / 2))
        L.append('    <g class="bars">')
        for j, name in enumerate(names):
            gx = x0 + j * group_w
            bx = gx + (group_w - pair_w) / 2
            L.append('      <g>')
            for x, v, cls, d in ((bx, gt[j], "bar--gt", D_GT),
                                 (bx + BAR_W + BAR_GAP, ours[j], "bar--ours",
                                  D_OURS)):
                top = base - v / 100.0 * PLOT_H
                if v > 0:
                    h = base - top
                    # The gradient goes in the inline style, not a fill=
                    # attribute: a presentation attribute loses to any CSS
                    # rule, and .chart--suites .bar--ours sets a default fill
                    # for the legend swatch.
                    L.append('        <rect class="bar rise %s" x="%.1f" '
                             'y="%.1f" width="%d" height="%.1f" rx="%.1f" '
                             'style="%s--d:%.2fs" />'
                             % (cls, x, top, BAR_W, h, min(3, h / 2),
                                'fill:url(#suitesBar%d);' % p
                                if cls == "bar--ours" else "", d))
                # The number lands as its bar settles, not before it has
                # anything to label.
                L.append('        <text class="val pop %s" x="%.1f" y="%.1f" '
                         'style="--d:%.2fs">%.1f</text>'
                         % (cls.replace("bar--", "val--"), x + BAR_W / 2,
                            top - 8, d + RISE * 0.7, v))
            L.append('        <text class="xlab" x="%.1f" y="%.1f">%s</text>'
                     % (gx + group_w / 2, base + XLAB_DY, name))
            L.append('      </g>')
        L += ['    </g>', '  </g>']

    L.append('</svg>')
    return "\n".join("      " + s for s in L)


def main():
    methods, panels = parse_tex()
    svg = build(methods, panels)
    html = open(HTML, encoding="utf-8").read()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html):
        sys.exit("markers not found in index.html -- insert them first")
    open(HTML, "w", encoding="utf-8").write(
        pat.sub(lambda _: "%s\n%s\n%s" % (BEGIN, svg, END), html))

    print("methods: %s | %s" % tuple(methods))
    for title, names, gt, ours in panels:
        print("  %-16s %s" % (title, "  ".join(
            "%s %.1f->%.1f" % (n, a, b) for n, a, b in zip(names, gt, ours))))


if __name__ == "__main__":
    main()
