#!/usr/bin/env python3
"""Generate the pick-success chart in the NIS ablation: Scripted against NIS, per profile.

tab:execution-search-ablation (a) in the paper, as grouped bars: one pair per
geometry/pose profile plus Overall. Baseline grey against our spectrum ramp,
baselines rising first -- the same reading as the real-world and LIBERO-PRO
charts, since it is the same kind of comparison.

Numbers are parsed from the paper source, not retyped. Re-run after they
change:

    python3 tools/make_pick_chart.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "index.html")
TEX = os.path.expanduser(
    "~/corl_2026/6a04a8918ed80a6693230556/secnew/experiments_final_2.tex")

BEGIN = "        <!-- >>> PICK CHART: generated by tools/make_pick_chart.py >>> -->"
END = "        <!-- <<< PICK CHART <<< -->"

RISE = 0.62
HOLD = 0.18
D_GT, D_OURS = 0.0, RISE + HOLD
LABEL = RISE * 0.7

VB_W, VB_H = 620, 336
PAD_L, PAD_R = 56, 14
Y_TOP, Y_BOT = 44, 254
Y_MAX = 108
GRID = (0, 25, 50, 75, 100)
BAR_W, BAR_GAP = 34, 6

X0, X1 = PAD_L, VB_W - PAD_R


def parse_tex():
    """Profile names from the header of table (a), values from its two rows."""
    t = open(TEX, encoding="utf-8").read()
    i = t.index(r"\label{tab:execution-search-ablation}")
    a = t[t.rindex(r"\textbf{(a)", 0, i):i]
    a = a[:a.index(r"\textbf{(b)")]
    head = re.search(r"Method\s*&(.*?)\\\\", a, re.S)
    rows = {m.group(1).strip(): m.group(2)
            for m in re.finditer(r"\n\s*([A-Za-z][^&\n]*?)\s*&([^\n]*?)\\\\", a)
            if not m.group(1).strip().startswith("Method")}
    if not head or len(rows) != 2:
        sys.exit("could not find the header or the two method rows of table (a)")
    profiles = [x.strip() for x in head.group(1).split("&")]

    def nums(cells):
        return [float(re.sub(r"\\best\{([^}]*)\}", r"\1", c).strip())
                for c in cells.split("&")]

    methods = list(rows)
    gt, ours = nums(rows[methods[0]]), nums(rows[methods[1]])
    if not (len(profiles) == len(gt) == len(ours)):
        sys.exit("shape mismatch: %d profiles, %d / %d values"
                 % (len(profiles), len(gt), len(ours)))
    return profiles, methods, gt, ours


def y_of(v):
    return Y_BOT - v / float(Y_MAX) * (Y_BOT - Y_TOP)


def xlab(x, y, name):
    """Two-word profile names break onto two lines; the group is too narrow for one."""
    words = name.split()
    if len(words) == 1:
        return '      <text class="xlab" x="%.1f" y="%d">%s</text>' % (x, y, name)
    return ('      <text class="xlab" x="%.1f" y="%d"><tspan x="%.1f">%s</tspan>'
            '<tspan x="%.1f" dy="14">%s</tspan></text>'
            % (x, y, x, words[0], x, " ".join(words[1:])))


def build(profiles, methods, gt, ours):
    n = len(profiles)
    group_w = (X1 - X0) / float(n)
    pair_w = 2 * BAR_W + BAR_GAP
    first = X0 + (group_w - pair_w) / 2 + BAR_W + BAR_GAP + BAR_W / 2
    last = first + (n - 1) * group_w

    L = ['<svg class="chart chart--sm chart--play chart--pick" '
         'viewBox="0 0 %d %d" role="img" '
         'aria-labelledby="pickTitle pickDesc">' % (VB_W, VB_H),
         '  <title id="pickTitle">Pick-up success rate by geometry and pose profile</title>',
         '  <desc id="pickDesc">Pick-up success rate of the learned Pick skill '
         'against a scripted grasp-proposal and motion-planning pipeline on '
         'held-out assets, per geometry and pose profile and overall: %s.</desc>'
         % "; ".join("%s %s vs %s" % (p, g, o) for p, g, o in zip(profiles, gt, ours)),
         '  <defs>',
         '    <linearGradient id="pickBar" gradientUnits="userSpaceOnUse" '
         'x1="%.1f" y1="0" x2="%.1f" y2="0">' % (first, last),
         '      <stop class="g-a" offset="0" />',
         '      <stop class="g-b" offset="1" />',
         '    </linearGradient>',
         '  </defs>',
         '  <g class="legend">']
    for x, cls, label in ((X0, "bar--gt", methods[0]),
                          (X0 + 120, "bar--ours", methods[1])):
        L += ['    <rect class="bar %s" x="%d" y="12" width="13" height="13" '
              'rx="3" />' % (cls, x),
              '    <text class="key" x="%d" y="23">%s</text>' % (x + 20, label)]
    L += ['  </g>', '  <g class="grid">']
    for v in GRID:
        y = y_of(v)
        L += ['    <line class="%s" x1="%d" y1="%.1f" x2="%d" y2="%.1f" />'
              % ("axis" if v == 0 else "rule", X0, y, X1, y),
              '    <text class="tick" x="%d" y="%.1f">%d</text>'
              % (X0 - 10, y + 4, v)]
    L += ['  </g>',
          '  <text class="ylab" transform="translate(16 %.1f) rotate(-90)">'
          'Pick-up success (%%)</text>' % ((Y_TOP + Y_BOT) / 2),
          '  <g class="bars">']
    for i, name in enumerate(profiles):
        gx = X0 + i * group_w
        bx = gx + (group_w - pair_w) / 2
        L.append('    <g>')
        for x, v, cls, d in ((bx, gt[i], "bar--gt", D_GT),
                             (bx + BAR_W + BAR_GAP, ours[i], "bar--ours",
                              D_OURS)):
            top = y_of(v)
            if v > 0:
                h = Y_BOT - top
                L.append('      <rect class="bar rise %s" x="%.1f" y="%.2f" '
                         'width="%d" height="%.2f" rx="%.1f" style="--d:%.2fs" '
                         '/>' % (cls, x, top, BAR_W, h, min(3, h / 2), d))
            L.append('      <text class="val %s pop" x="%.1f" y="%.2f" '
                     'style="--d:%.2fs">%s</text>'
                     % (cls.replace("bar--", "val--"), x + BAR_W / 2, top - 12,
                        d + LABEL, ("%.1f" % v)))
        L.append(xlab(gx + group_w / 2, Y_BOT + 22, name))
        L.append('    </g>')
    L += ['  </g>',
          '  <text class="atitle" x="%.1f" y="%d">Geometry / pose profile</text>'
          % ((X0 + X1) / 2, Y_BOT + 66),
          '</svg>']
    return "\n".join("        " + s for s in L)


def main():
    profiles, methods, gt, ours = parse_tex()
    html = open(HTML, encoding="utf-8").read()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html):
        sys.exit("markers not found in index.html -- insert them first")
    open(HTML, "w", encoding="utf-8").write(
        pat.sub(lambda _: "%s\n%s\n%s" % (BEGIN, build(profiles, methods, gt, ours),
                                          END), html))
    print("%s vs %s" % tuple(methods))
    for n, a, b in zip(profiles, gt, ours):
        print("  %-18s %5.1f -> %5.1f   %+.1f" % (n, a, b, b - a))


if __name__ == "__main__":
    main()
