#!/usr/bin/env python3
"""Generate the real-world scenario chart: PT against LST+PT, per scenario.

The table above it carries all twelve tasks; this pulls out the one comparison
the table is making and shows it as bars, because the table's own summary --
the Average row -- is three pairs of numbers a reader otherwise has to find at
the bottom of a 6-column grid and subtract by hand.

Baseline grey against our spectrum ramp, baselines rising first, exactly as in
the LIBERO-PRO charts: this is the same kind of comparison, so it gets the same
reading.

Numbers are parsed from the paper source, not retyped. Re-run after they
change:

    python3 tools/make_realworld_chart.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "index.html")
TEX = os.path.expanduser(
    "~/corl_2026/6a04a8918ed80a6693230556/sec/exps_katef.tex")

BEGIN = "        <!-- >>> REALWORLD CHART: generated by tools/make_realworld_chart.py >>> -->"
END = "        <!-- <<< REALWORLD CHART <<< -->"

RISE = 0.62
HOLD = 0.18
D_GT, D_OURS = 0.0, RISE + HOLD
LABEL = RISE * 0.7

VB_W, VB_H = 620, 322
PAD_L, PAD_R = 56, 14
Y_TOP, Y_BOT = 44, 254
Y_MAX = 108
GRID = (0, 25, 50, 75, 100)
BAR_W, BAR_GAP = 60, 10

X0, X1 = PAD_L, VB_W - PAD_R


def parse_tex():
    """Scenario names from the \\multicolumn band, values from Average."""
    t = open(TEX, encoding="utf-8").read()
    i = t.index(r"\label{tab:realworld}")
    b = t[max(0, i - 4000):i]
    b = b[b.rindex(r"\begin{tabular}"):]

    band = re.findall(r"\\multicolumn\{2\}\{c\}\{([^}]*)\}", b)
    m = re.search(r"\\multicolumn\{2\}\{l\}\{Average\}(.*?)\\\\", b, re.S)
    if not band or not m:
        sys.exit("could not find the scenario band or the Average row")
    cells = [re.sub(r"\\best\{([^}]*)\}", r"\1",
                    re.sub(r"\\(up|dn)\{[^}]*\}", "", c)).replace("~", "").strip()
             for c in m.group(1).split("&") if c.strip()]
    vals = [float(c) for c in cells]

    heads = re.search(r"&\s*Instruction\s*&(.*?)\\\\", b)
    methods = [x.strip() for x in heads.group(1).split("&")][:2]
    if len(band) * 2 != len(vals) or len(methods) != 2:
        sys.exit("shape mismatch: %d scenarios, %d values, %d methods"
                 % (len(band), len(vals), len(methods)))
    return band, methods, vals[0::2], vals[1::2]


def y_of(v):
    return Y_BOT - v / float(Y_MAX) * (Y_BOT - Y_TOP)


def build(band, methods, gt, ours):
    n = len(band)
    group_w = (X1 - X0) / float(n)
    pair_w = 2 * BAR_W + BAR_GAP
    first = X0 + (group_w - pair_w) / 2 + BAR_W + BAR_GAP + BAR_W / 2
    last = first + (n - 1) * group_w

    L = ['<svg class="chart chart--sm chart--play chart--rw" '
         'viewBox="0 0 %d %d" role="img" '
         'aria-labelledby="rwTitle rwDesc">' % (VB_W, VB_H),
         '  <title id="rwTitle">Real-world success rate by scenario</title>',
         '  <desc id="rwDesc">Average success rate over twelve real-world '
         'tasks in each of three scenarios, comparing post-training alone '
         'against large-scale simulation training followed by the same '
         'post-training. The second wins every scenario, by most under '
         'swapped objects, where post-training alone reaches %s per cent.'
         '</desc>' % gt[1],
         '  <defs>',
         '    <linearGradient id="rwBar" gradientUnits="userSpaceOnUse" '
         'x1="%.1f" y1="0" x2="%.1f" y2="0">' % (first, last),
         '      <stop class="g-a" offset="0" />',
         '      <stop class="g-b" offset="1" />',
         '    </linearGradient>',
         '  </defs>',
         '  <g class="legend">']
    for x, cls, label in ((X0, "bar--gt", methods[0]),
                          (X0 + 120, "bar--ours", methods[1])):
        L += ['    <rect class="bar %s" x="%d" y="12" width="13" height="13" '
              'rx="3" />' % (cls, x),
              '    <text class="key" x="%d" y="23">%s</text>' % (x + 20, label)]
    L += ['  </g>', '  <g class="grid">']
    for v in GRID:
        y = y_of(v)
        L += ['    <line class="%s" x1="%d" y1="%.1f" x2="%d" y2="%.1f" />'
              % ("axis" if v == 0 else "rule", X0, y, X1, y),
              '    <text class="tick" x="%d" y="%.1f">%d</text>'
              % (X0 - 10, y + 4, v)]
    L += ['  </g>',
          '  <text class="ylab" transform="translate(16 %.1f) rotate(-90)">'
          'Success rate (%%)</text>' % ((Y_TOP + Y_BOT) / 2),
          '  <g class="bars">']
    for i, name in enumerate(band):
        gx = X0 + i * group_w
        bx = gx + (group_w - pair_w) / 2
        L.append('    <g>')
        for x, v, cls, d in ((bx, gt[i], "bar--gt", D_GT),
                             (bx + BAR_W + BAR_GAP, ours[i], "bar--ours",
                              D_OURS)):
            top = y_of(v)
            if v > 0:
                h = Y_BOT - top
                L.append('      <rect class="bar rise %s" x="%.1f" y="%.2f" '
                         'width="%d" height="%.2f" rx="%.1f" style="--d:%.2fs" '
                         '/>' % (cls, x, top, BAR_W, h, min(3, h / 2), d))
            L.append('      <text class="val %s pop" x="%.1f" y="%.2f" '
                     'style="--d:%.2fs">%s</text>'
                     % (cls.replace("bar--", "val--"), x + BAR_W / 2, top - 12,
                        d + LABEL, v))
        L.append('      <text class="xlab" x="%.1f" y="%d">%s</text>'
                 % (gx + group_w / 2, Y_BOT + 24, name))
        L.append('    </g>')
    L += ['  </g>',
          '  <text class="atitle" x="%.1f" y="%d">Real-world scenario</text>'
          % ((X0 + X1) / 2, Y_BOT + 50),
          '</svg>']
    return "\n".join("        " + s for s in L)


def main():
    band, methods, gt, ours = parse_tex()
    html = open(HTML, encoding="utf-8").read()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html):
        sys.exit("markers not found in index.html -- insert them first")
    open(HTML, "w", encoding="utf-8").write(
        pat.sub(lambda _: "%s\n%s\n%s" % (BEGIN, build(band, methods, gt, ours),
                                          END), html))
    print("%s vs %s" % tuple(methods))
    for n, a, b in zip(band, gt, ours):
        print("  %-18s %5.1f -> %5.1f   %+.1f" % (n, a, b, b - a))


if __name__ == "__main__":
    main()
