#!/usr/bin/env python3
"""Generate the Verifier-vs-no-Verifier panel of the Ablations section.

Two slides behind the page's left/right carousel (.carousel in css/style.css,
[data-carousel] in js/nav.js):

  Search guidance    Three search animations, one per configuration of
                     tab:verifier-ablation (a), over the table itself.
  Success detection  tab:verifier-ablation (b), with the handcrafted success
                     rules it is scored against (app:verifier_ablation).

The animations speak the visual language of the MCTS-vs-linear panel
(tools/make_search_ablation.py, whose element model and geometry helpers are
imported here): dark space panel, small dark nodes, amber for an edge being
grown, teal/rose verdicts, an indigo token running down to the node selected
next, an amber one running back up with a value, the teal->indigo->amber
gradient for the accepted path.

  w/ Verifier, w/o Rollout   the verifier scores each new node on the spot;
                             the score is backed up and the best frontier node
                             is expanded next, so the search walks straight in.
  w/o Verifier, w/o Rollout  no intermediate reward: children are "?", the next
                             node is drawn uniformly from the frontier, and only
                             a terminal step says whether a branch worked.
  w/o Verifier, w/ Rollout   standard MCTS: every new node is rolled out to a
                             terminal state, the outcome is backed up and the
                             rollout thrown away -- each step costs a full chain.

Each loops on its own clock (they are not time-matched); what each costs per
successful trajectory is the label it ends on, read from the paper.

Numbers are parsed from the paper source, not retyped. Re-run after they
change:

    python3 tools/make_verifier_ablation.py [--frames DIR]

--frames writes verifier_ablation_frames.png into DIR (keep it outside the
repo): stills rendered with cairosvg, since there is no browser on the cluster.
"""
import argparse
import io
import math
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import chartlib  # noqa: E402
import make_search_ablation as sa  # noqa: E402  (element model, geometry, palette)

ROOT = Path(__file__).resolve().parent.parent
DEF_HTML = ROOT / "index.html"
DEF_CSS = ROOT / "css" / "style.css"
TEX = Path.home() / "corl_2026/6a04a8918ed80a6693230556/secnew/experiments_final_2.tex"

BEGIN_H = "<!-- >>> VERIFIER ABLATION — generated by tools/make_verifier_ablation.py, do not edit by hand >>> -->"
END_H = "<!-- <<< VERIFIER ABLATION <<< -->"
BEGIN_C = "/* >>> VERIFIER ABLATION — generated by tools/make_verifier_ablation.py, do not edit by hand >>> */"
END_C = "/* <<< VERIFIER ABLATION <<< */"

SPACE, SW_LINE, LABEL = sa.SPACE, sa.SW_LINE, sa.LABEL
NODE_FILL, NODE_STROKE = sa.NODE_FILL, sa.NODE_STROKE
TEAL, INDIGO, AMBER, ROSE = sa.TEAL, sa.INDIGO, sa.AMBER, sa.ROSE
MONO, R, f = sa.MONO, sa.R, sa.f

VB_W, VB_H = 400, 225
X = [30, 110, 190, 270, 350]           # root, then depth 1..4 (every task needs >= 4 steps)
ROOT_XY = (X[0], 105)

EXEC, VERDICT = 0.8, 0.6               # one skill execution, its verdict landing VERDICT in
SEL, BACK = 0.45, 0.5                  # selection token down, value token up
R_ROLL = 4.5                           # rollout nodes are smaller: simulated, then discarded


# ----------------------------------------------------------------------------
# A clock per animation: the fades, the reduced-motion still and the keyframe
# percentages all hang off its cycle.
# ----------------------------------------------------------------------------
class Clock:
    def __init__(self, cycle):
        self.cycle = cycle
        self.f0, self.f1 = cycle - 1.4, cycle - 0.7   # everything clears before the loop restarts
        self.hold = cycle - 2.0                      # the still shown under prefers-reduced-motion

    def appear(self, t_in, dur=0.18, level=1.0, dim=None):
        p = [(0.0, 0.0), (t_in, 0.0), (t_in + dur, level)]
        if dim:
            t_dim, to = dim
            p += [(t_dim, level), (t_dim + 0.5, to)]
            level = to
        return p + [(self.f0, level), (self.f1, 0.0), (self.cycle, 0.0)]

    def window(self, t_in, t_out, dur=0.18, out=0.3):
        """Shown from t_in, gone again by t_out + out -- a rollout that is discarded."""
        return [(0.0, 0.0), (t_in, 0.0), (t_in + dur, 1.0), (t_out, 1.0), (t_out + out, 0.0),
                (self.cycle, 0.0)]

    def pop(self, t_in, lo=0.6):
        return [(0.0, lo), (t_in, lo), (t_in + 0.12, 1.15), (t_in + 0.26, 1.0), (self.cycle, 1.0)]

    def once(self, t_in, dur=0.18):
        return [(0.0, 0.0), (t_in, 0.0), (t_in + dur, 1.0), (self.cycle, 1.0)]

    def pct(self, t):
        return f(t / self.cycle * 100) + "%"


# ----------------------------------------------------------------------------
# Builders (the search-ablation ones, on a per-animation clock)
# ----------------------------------------------------------------------------
def edge(ck, uid, p, q, t_draw, t_settle, dim=None):
    s, c1, c2, e = sa.seg(p, q)
    d = f"M{f(s[0])},{f(s[1])} C{f(c1[0])},{f(c1[1])} {f(c2[0])},{f(c2[1])} {f(e[0])},{f(e[1])}"
    L = sa.plen(sa.cubic_pts(s, c1, c2, e))
    return (sa.El(uid, "path", {"d": d, "fill": "none", "stroke": SW_LINE, "stroke-width": "1.8",
                                "stroke-linecap": "round"}, dash=f"{f(L)} {f(L)}")
            .track("o", ck.appear(t_draw, dur=0.05, dim=dim))
            .track("d", [(0.0, L), (t_draw, L), (t_draw + 0.45, 0.0), (ck.cycle, 0.0)])
            .track("c", [(0.0, AMBER), (t_settle, AMBER), (t_settle + 0.4, SW_LINE), (ck.cycle, SW_LINE)]))


def chip(cx, cy, text, fill):
    return (f'<text x="{f(cx)}" y="{f(cy - 12)}" text-anchor="middle" font-family="{MONO}" '
            f'font-size="9.5" font-weight="700" fill="{fill}">{text}</text>')


def node(ck, uid, cx, cy, kind, t_show, t_verdict, text=None, dim=None):
    """kind: ok / fail (terminal verdicts, with a glyph), hi / lo (a verifier score,
    ring only, the score above it), unknown (grey ring, '?')."""
    ring = (f'<circle cx="{f(cx)}" cy="{f(cy)}" r="{R}" fill="{NODE_FILL}" stroke="{NODE_STROKE}" '
            f'stroke-width="1.6"/>')
    col = {"ok": TEAL, "hi": TEAL, "fail": ROSE, "lo": ROSE}.get(kind)
    body = ""
    if col:
        body = (f'<circle cx="{f(cx)}" cy="{f(cy)}" r="{R}" fill="{NODE_FILL}" stroke="{col}" '
                f'stroke-width="1.8"/>')
    if kind == "ok":
        body += (f'<path d="{sa.check_d(cx, cy)}" fill="none" stroke="{TEAL}" stroke-width="1.6" '
                 f'stroke-linecap="round" stroke-linejoin="round"/>')
    elif kind == "fail":
        body += (f'<path d="{sa.cross_d(cx, cy)}" fill="none" stroke="{ROSE}" stroke-width="1.6" '
                 f'stroke-linecap="round"/>')
    if text is not None:
        body += chip(cx, cy, text, col or LABEL)
    verdict = (sa.El(uid + "-v", "g", children=[body], origin=(cx, cy))
               .track("o", ck.once(t_verdict)).track("s", ck.pop(t_verdict)))
    return sa.El(uid, "g", children=[ring, verdict]).track("o", ck.appear(t_show, dim=dim))


def value_chip(ck, uid, cx, cy, text, fill, t, dim=None):
    """A value that lands on a node later than the node itself (a rollout outcome)."""
    return sa.El(uid, "g", children=[chip(cx, cy, text, fill)]).track("o", ck.appear(t, dim=dim))


def token(ck, uid, points, t_arrive, up=False):
    """Indigo dash running down to the node selected next; amber back up with a value."""
    d, L = sa.chain_path(points)
    dur = max(0.25, L / 600) if not up else BACK
    t0 = t_arrive - dur
    near, far = 16.0, -(L - 16)
    a, b = (far, near) if up else (near, far)
    return (sa.El(uid, "path", {"d": d, "fill": "none", "stroke": AMBER if up else INDIGO,
                                "stroke-width": "3", "stroke-linecap": "round"}, dash=f"16 {f(L + 32)}")
            .track("o", [(0.0, 0.0), (t0, 0.0), (t0 + 0.03, 1.0), (t_arrive, 1.0), (t_arrive + 0.06, 0.0),
                         (ck.cycle, 0.0)])
            .track("d", [(0.0, a), (t0, a), (t_arrive, b), (ck.cycle, b)]))


def glow(ck, uid, points, t, gid):
    d, L = sa.chain_path(points)
    return (sa.El(uid, "path", {"d": d, "fill": "none", "stroke": f"url(#{gid})", "stroke-width": "3",
                                "stroke-linecap": "round", "stroke-linejoin": "round"},
                  dash=f"{f(L)} {f(L)}", cls="va-glow")
            .track("o", ck.appear(t, dur=0.05)).track("d", [(0.0, L), (t, L), (t + 1.0, 0.0), (ck.cycle, 0.0)]))


def goal(ck, uid, cx, cy, t):
    body = (f'<circle cx="{f(cx)}" cy="{f(cy)}" r="7.5" fill="{AMBER}"/>'
            f'<path d="{sa.check_d(cx, cy)}" fill="none" stroke="{SPACE}" stroke-width="1.9" '
            f'stroke-linecap="round" stroke-linejoin="round"/>')
    tr = ck.appear(t)
    tr[-3:] = [(ck.f1, 1.0), (ck.f1 + 0.3, 0.0), (ck.cycle, 0.0)]   # outlives the verdict it covers
    return sa.El(uid, "g", children=[body], origin=(cx, cy), cls="va-goal").track("o", tr).track("s", ck.pop(t))


def time_label(ck, uid, seconds, t):
    return (sa.El(uid, "g", children=[
        f'<text x="{VB_W - 8}" y="{VB_H - 9}" text-anchor="end" font-family="{MONO}" font-size="12" '
        f'font-weight="700" letter-spacing="1" fill="{AMBER}">{seconds} S / SUCCESS TRAJ.</text>'])
        .track("o", ck.appear(t, dur=0.3)))


def root():
    cx, cy = ROOT_XY
    return (f'<circle cx="{cx}" cy="{cy}" r="{R}" fill="{NODE_FILL}" stroke="{NODE_STROKE}" stroke-width="1.6"/>'
            + sa.label(cx, cy + 22, "START"))


class Tree:
    """Node positions and parents for one animation, with path helpers."""

    def __init__(self, pos, parent):
        self.pos, self.parent = dict(pos, R=ROOT_XY), parent

    def path(self, key):
        chain = [key]
        while chain[-1] != "R":
            chain.append(self.parent[chain[-1]])
        return [self.pos[k] for k in reversed(chain)]


def finish(ck, P, tree, path_pts, t_glow, gid, seconds):
    return ([glow(ck, f"{P}-glow", path_pts, t_glow, gid),
             goal(ck, f"{P}-goal", *path_pts[-1], t_glow + 1.0),
             time_label(ck, f"{P}-time", seconds, t_glow + 1.3)])


# ----------------------------------------------------------------------------
# (i) w/ Verifier, w/o Rollout
# ----------------------------------------------------------------------------
def build_verifier(seconds):
    P = "va-v"
    tree = Tree({"A": (110, 70), "A2": (110, 140), "B": (190, 70), "B2": (190, 125),
                 "C2": (270, 30), "C": (270, 70), "D": (350, 70), "D2": (350, 125)},
                {"A": "R", "A2": "R", "B": "A", "B2": "A", "C": "B", "C2": "B", "D": "C", "D2": "C"})
    # (parent, children in execution order with (kind, score shown), best child)
    plan = [("R", [("A", "hi", "0.8"), ("A2", "lo", "0.3")], "A"),
            ("A", [("B", "hi", "0.9"), ("B2", "lo", "0.2")], "B"),
            ("B", [("C2", "lo", "0.4"), ("C", "hi", "0.7")], "C"),
            ("C", [("D", "ok", None), ("D2", "fail", None)], None)]
    win = ["R", "A", "B", "C", "D"]
    t, sched = 0.5, []
    for parent, kids, best in plan:
        sched.append((t, parent, kids, best))
        t_done = t + 2 * EXEC
        t = t_done + BACK + 0.1 + SEL + 0.05 if best else t_done
    t_glow = sched[-1][0] + VERDICT + EXEC + 0.15     # after both children of the last expansion are judged
    ck = Clock(t_glow + 4.3)
    dim = (t_glow, 0.35)
    edges, nodes, tokens = [], [], []
    for t0, parent, kids, best in sched:
        if parent != "R":
            tokens.append(token(ck, f"{P}-sel-{parent}", tree.path(parent), t0 - 0.05))
        for k, (child, kind, score) in enumerate(kids):
            t_v = t0 + VERDICT + k * EXEC
            keep = child in win
            edges.append(edge(ck, f"{P}-e-{child}", tree.pos[parent], tree.pos[child], t0 + k * EXEC, t_v,
                              dim=None if keep else dim))
            nodes.append(node(ck, f"{P}-{child}", *tree.pos[child], kind, t0 + k * EXEC + 0.3, t_v, score,
                              dim=None if keep else dim))
        if best:
            tokens.append(token(ck, f"{P}-up-{best}", tree.path(best), t0 + 2 * EXEC + BACK, up=True))
    pts = [tree.pos[k] for k in win]
    els = ([sa.gradient("vaWinV", pts[0][0], pts[-1][0])] + edges + tokens + [root()] + nodes
           + finish(ck, P, tree, pts, t_glow, "vaWinV", seconds))
    return ck, els


# ----------------------------------------------------------------------------
# (ii) w/o Verifier, w/o Rollout
# ----------------------------------------------------------------------------
def build_uniform(seconds):
    P = "va-u"
    tree = Tree({"A": (110, 65), "A2": (110, 150), "B2": (190, 40), "B": (190, 90), "E": (190, 135),
                 "E2": (190, 180), "C2": (270, 40), "C": (270, 85), "F": (270, 135), "F2": (270, 178),
                 "D": (350, 85), "D2": (350, 40), "G": (350, 135), "G2": (350, 178)},
                {"A": "R", "A2": "R", "B": "A", "B2": "A", "E": "A2", "E2": "A2", "C": "B", "C2": "B",
                 "F": "E", "F2": "E", "D": "C", "D2": "C", "G": "F", "G2": "F"})
    # Frontier drawn at random: children carry no score ("?"); only depth 4 is judged.
    plan = [("R", [("A", "unknown"), ("A2", "unknown")]),
            ("A2", [("E", "unknown"), ("E2", "unknown")]),
            ("A", [("B", "unknown"), ("B2", "unknown")]),
            ("E", [("F", "unknown"), ("F2", "unknown")]),
            ("F", [("G", "fail"), ("G2", "fail")]),
            ("B", [("C", "unknown"), ("C2", "unknown")]),
            ("C", [("D", "ok"), ("D2", "fail")])]
    win = ["R", "A", "B", "C", "D"]
    t, sched = 0.5, []
    for parent, kids in plan:
        sched.append((t, parent, kids))
        t += 2 * EXEC + SEL + 0.1
    t_glow = sched[-1][0] + VERDICT + EXEC + 0.15
    ck = Clock(t_glow + 4.3)
    dim = (t_glow, 0.35)
    edges, nodes, tokens = [], [], []
    for t0, parent, kids in sched:
        if parent != "R":
            tokens.append(token(ck, f"{P}-sel-{parent}", tree.path(parent), t0 - 0.05))
        for k, (child, kind) in enumerate(kids):
            t_v = t0 + VERDICT + k * EXEC
            keep = child in win
            edges.append(edge(ck, f"{P}-e-{child}", tree.pos[parent], tree.pos[child], t0 + k * EXEC, t_v,
                              dim=None if keep else dim))
            nodes.append(node(ck, f"{P}-{child}", *tree.pos[child], kind, t0 + k * EXEC + 0.3, t_v,
                              "?" if kind == "unknown" else None, dim=None if keep else dim))
    pts = [tree.pos[k] for k in win]
    els = ([sa.gradient("vaWinU", pts[0][0], pts[-1][0])] + edges + tokens + [root()] + nodes
           + finish(ck, P, tree, pts, t_glow, "vaWinU", seconds))
    return ck, els


# ----------------------------------------------------------------------------
# (iii) w/o Verifier, w/ Rollout
# ----------------------------------------------------------------------------
def rollout(ck, uid, start, steps, ok, t0, t_gone):
    """Execute the downstream skills from `start` to depth 4, one EXEC each: small
    dashed nodes along the node's own row, the terminal judged. Discarded at
    t_gone unless it is the successful one (t_gone None)."""
    x0, y = start
    xs = [x for x in X if x > x0][:steps]
    out, prev = [], x0
    for k, x in enumerate(xs):
        t_in = t0 + k * EXEC
        last = k == len(xs) - 1
        g = (f'<path d="M{f(prev + (R if k == 0 else R_ROLL))},{f(y)} L{f(x - R_ROLL)},{f(y)}" stroke="{NODE_STROKE}" '
             f'stroke-width="1.3" stroke-dasharray="2.5 3.5" stroke-linecap="round" fill="none"/>'
             f'<circle cx="{f(x)}" cy="{f(y)}" r="{R_ROLL}" fill="{NODE_FILL}" stroke="{NODE_STROKE}" '
             f'stroke-width="1.3" stroke-dasharray="2 2"/>')
        if last:
            col = TEAL if ok else ROSE
            glyph = (f'<path d="{sa.check_d(x, y, 0.8)}" fill="none" stroke="{col}" stroke-width="1.5" '
                     f'stroke-linecap="round" stroke-linejoin="round"/>' if ok else
                     f'<path d="{sa.cross_d(x, y, 2.1)}" fill="none" stroke="{col}" stroke-width="1.5" '
                     f'stroke-linecap="round"/>')
            g += (f'<circle cx="{f(x)}" cy="{f(y)}" r="{R_ROLL}" fill="{NODE_FILL}" stroke="{col}" '
                  f'stroke-width="1.5"/>' + glyph)
        el = sa.El(f"{uid}-{k}", "g", children=[g])
        el.track("o", ck.appear(t_in, dur=0.25) if t_gone is None else ck.window(t_in, t_gone))
        out.append(el)
        prev = x
    return out, [(x, y) for x in xs]


def build_rollout(seconds):
    P = "va-r"
    tree = Tree({"A": (110, 65), "A2": (110, 150), "B2": (190, 30), "B": (190, 100), "E": (190, 150)},
                {"A": "R", "A2": "R", "B": "A", "B2": "A", "E": "A2"})
    depth = {"A": 1, "A2": 1, "B": 2, "B2": 2, "E": 2}
    # (parent, children in execution order with their rollout outcome). All zero
    # so far means the next pick is uniform too; the E rollout finally succeeds.
    plan = [("R", [("A", False), ("A2", False)]),
            ("A", [("B2", False), ("B", False)]),
            ("A2", [("E", True)])]
    edges, nodes, tokens, rolls, chips = [], [], [], [], []
    t = 0.5
    events = []
    for parent, kids in plan:
        if parent != "R":
            events.append(("sel", parent, t - 0.05))
        for child, ok in kids:
            steps = 4 - depth[child]
            t_exec = t
            t_roll = t + EXEC
            t_term = t_roll + (steps - 1) * EXEC + VERDICT
            events.append(("child", parent, child, ok, t_exec, t_roll, t_term))
            if ok:
                t_glow = t_term + 0.25
                break
            t = t_term + 0.1 + BACK + 0.1
        else:
            t += SEL
            continue
        break
    ck = Clock(t_glow + 4.3)
    win_nodes = ["R", "A2", "E"]
    dim = (t_glow, 0.35)
    win_tail = []
    for ev in events:
        if ev[0] == "sel":
            tokens.append(token(ck, f"{P}-sel-{ev[1]}", tree.path(ev[1]), ev[2]))
            continue
        _, parent, child, ok, t_exec, t_roll, t_term = ev
        keep = child in win_nodes
        edges.append(edge(ck, f"{P}-e-{child}", tree.pos[parent], tree.pos[child], t_exec, t_exec + VERDICT,
                          dim=None if keep else dim))
        nodes.append(node(ck, f"{P}-{child}", *tree.pos[child], "unknown", t_exec + 0.3, t_exec + VERDICT,
                          None, dim=None if keep else dim))
        steps = 4 - depth[child]
        t_gone = None if ok else t_term + 0.1 + BACK
        chain, pts = rollout(ck, f"{P}-roll-{child}", tree.pos[child], steps, ok, t_roll, t_gone)
        rolls += chain
        if ok:
            win_tail = pts
        else:
            tokens.append(token(ck, f"{P}-up-{child}", tree.path(child), t_term + 0.1 + BACK, up=True))
            chips.append(value_chip(ck, f"{P}-val-{child}", *tree.pos[child], "0", ROSE,
                                    t_term + 0.1 + BACK, dim=None if keep else dim))
    pts = [tree.pos[k] for k in win_nodes] + win_tail
    els = ([sa.gradient("vaWinR", pts[0][0], pts[-1][0])] + edges + rolls + tokens + [root()] + nodes + chips
           + finish(ck, P, tree, pts, t_glow, "vaWinR", seconds))
    return ck, els


# ----------------------------------------------------------------------------
# Paper tables
# ----------------------------------------------------------------------------
def parse_tex():
    t = TEX.read_text(encoding="utf-8")
    i = t.index(r"\label{tab:verifier-ablation}")
    blk = t[t.rindex(r"\textbf{(a)", 0, i):i]
    a, b = blk.split(r"\textbf{(b)")

    configs = re.findall(r"\\multicolumn\{3\}\{c\}\{(w/[^}]*)\}", a)
    ks = re.findall(r"\$K\{\\le\}(\d+)\$", a)[:3]
    unbest = lambda c: re.sub(r"\\best\{([^}]*)\}", r"\1", c).strip()
    sr = re.search(r"Avg\. Success Rate[^&]*&(.*?)\\\\", a, re.S).group(1)
    sr = [unbest(c) for c in sr.split("&")]
    tm = re.search(r"Time / Success Traj[^&]*&(.*?)\\\\", a, re.S).group(1)
    tm = [unbest(re.sub(r"\\multicolumn\{3\}\{c\}\{(.*)\}", r"\1", c)) for c in tm.split("&")]
    if len(configs) != 3 or len(ks) != 3 or len(sr) != 9 or len(tm) != 3:
        sys.exit("unexpected shape in tab:verifier-ablation (a)")
    search = [(c, sr[3 * j:3 * j + 3], tm[j]) for j, c in enumerate(configs)]

    head = re.search(r"Setting\s*&(.*?)\\\\", b, re.S).group(1)
    cols = [x.strip() for x in head.split("&")]
    rows = []
    for m in re.finditer(r"\n\s*([A-Za-z+][^&\n]*?)\s*&([^\n]*?)\\\\", b):
        name = m.group(1).strip()
        if name.startswith("Setting"):
            continue
        rows.append((name, [unbest(c) for c in m.group(2).split("&")]))
    if len(rows) != 2 or any(len(v) != len(cols) for _, v in rows):
        sys.exit("unexpected shape in tab:verifier-ablation (b)")
    return ks, search, cols, rows


def search_charts(ks, search):
    """tab:verifier-ablation (a) as two charts: the success rates share one axis,
    the wall-clock time is a different unit and gets its own."""
    names = [c for c, _, _ in search]
    cls = ["bar--ours", "bar--gt", "bar--gt2"]
    rates = chartlib.grouped_bars(
        name="verSearch", gradient="verSearchBar",
        groups=[f"K&nbsp;&le;&nbsp;{k}" for k in ks],
        series=[{"label": n, "cls": c, "values": [float(v) for v in sr]}
                for (n, sr, _), c in zip(search, cls)],
        ylab="Avg. success rate (%)", atitle="Search budget (maximum depth)",
        ymax=108, grid=(0, 25, 50, 75, 100), fmt="%.1f", vb_w=660, bar_w=30,
        title="Search success rate by budget and verifier configuration",
        desc="Average success rate at each maximum depth: " + "; ".join(
            "%s %s" % (n, ", ".join("K &le; %s %s%%" % (k, v) for k, v in zip(ks, sr)))
            for n, sr, _ in search) + ".")
    times = [float(t) for _, _, t in search]
    top = max(times) * 1.12
    time = chartlib.grouped_bars(
        name="verTime", gradient="verTimeBar",
        groups=[n.replace("w/ ", "w/&nbsp;").replace("w/o ", "w/o&nbsp;") for n in names],
        series=[{"label": "", "cls": "bar--ours", "cls_per_group": cls, "values": times}],
        ylab="Time / success traj. (s)", atitle="Cost of one successful trajectory",
        ymax=top, grid=tuple(i * 1000 for i in range(int(top // 1000) + 1)),
        fmt="%.0f", vb_w=660, bar_w=70, legend=False,
        title="Wall-clock time per successful trajectory",
        desc="Seconds per successful trajectory: " + "; ".join(
            "%s %s" % (n, t) for n, t in zip(names, times)) + ".")
    t_ver, t_uni, t_roll = times
    return (['<div class="chart-row">',
             '  <figure class="figure">',
             '    <div class="chart-wrap" role="region" tabindex="0" aria-label="Search success rate by budget">']
            + [rates] + ['    </div>', '  </figure>',
             '  <figure class="figure">',
             '    <div class="chart-wrap" role="region" tabindex="0" aria-label="Time per successful trajectory">']
            + [time] + ['    </div>', '  </figure>', '</div>',
             '<p class="table-note">Six long-horizon tasks of four or more skill steps, each searched ten times per '
             'maximum depth <i>K</i>. <b>Verifier-guided search succeeds most often at every budget and takes the '
             'least time per successful trajectory.</b> Without intermediate rewards, the next node is drawn at '
             f'random from the frontier and a successful trajectory takes {t_uni / t_ver:.1f}&times; as long; '
             'rollout-based search pays for a full chain of skill executions on every new node and takes '
             f'{t_roll / t_ver:.1f}&times; as long.</p>'])


RULES = [
    ("Pick up", "the object is lifted at least 15&nbsp;cm above its initial height, with fingertip contact "
                "maintained between gripper and object."),
    ("Place", "the center of the source object lies inside the target container's bounding box."),
    ("Orientation aware &amp; straighten", "additionally, the object's local <i>z</i>-axis must be aligned with "
                                           "world <i>+z</i> within a cosine threshold &mdash; e.g. placing an "
                                           "elongated object into a thin container, or standing a lying object up."),
]


def detect_chart(cols, rows):
    """tab:verifier-ablation (b) as grouped bars, with the handcrafted rules under it."""
    chart = chartlib.grouped_bars(
        name="verDetect", gradient="verDetectBar",
        groups=[c.replace(" ", "&nbsp;", 0) for c in cols],
        series=[{"label": name, "cls": "bar--gt" if j == 0 else "bar--ours",
                 "values": [float(v) for v in vals]}
                for j, (name, vals) in enumerate(rows)],
        ylab="Detection accuracy (%)", atitle="Task type", ymax=108,
        grid=(0, 25, 50, 75, 100), fmt="%.1f", vb_w=660, bar_w=34,
        title="Final success detection accuracy by task type",
        desc="Accuracy against handcrafted labels per task type: " + "; ".join(
            "%s %s" % (n, ", ".join("%s %s%%" % (c, v) for c, v in zip(cols, vals)))
            for n, vals in rows) + ".")
    return (['<figure class="figure">',
             '  <div class="chart-wrap chart-wrap--sm" role="region" tabindex="0" aria-label="Final success detection accuracy">']
            + [chart] + ['  </div>', '</figure>',
             '<p class="table-note">Accuracy (%) of the final verdict against handcrafted labels, 50 tasks per type, '
             'one search each. <b>Image-only</b>: the instruction plus <code>front</code> and <code>top</code> views of '
             'the initial and final scenes (four 512&times;512 images). <b>+ Privileged States</b>: the same images plus '
             "each object's 3D center and axis-aligned bounding box and the gripper's contact list.</p>",
             '<h4 class="ver-rules__title">Handcrafted success conditions</h4>',
             '<ul class="ver-rules">'] + [f"  <li><b>{k}</b> &mdash; {v}</li>" for k, v in RULES] + ['</ul>'])


# ----------------------------------------------------------------------------
# Rendering
# ----------------------------------------------------------------------------
ANIMS = [("v", "w/ Verifier, w/o Rollout", "verifier scores each new node &middot; best frontier node next",
          "Verifier-guided search: every new node is scored by the verifier, the score is backed up the tree, "
          "and the best-scoring frontier node is expanded next, so the search walks straight to the goal."),
         ("u", "w/o Verifier, w/o Rollout", "no intermediate reward &middot; frontier node drawn at random",
          "Search without intermediate rewards: new nodes carry no score, the next node is drawn uniformly "
          "from the frontier, and only terminal steps reveal whether a branch worked."),
         ("r", "w/o Verifier, w/ Rollout", "every new node rolled out to the end &middot; outcome backed up",
          "Rollout-based search: every new node is rolled out through the remaining skills to a terminal "
          "state, the outcome is backed up and the rollout discarded, until a rollout finally succeeds.")]


def html_block(anims, ks, search, cols, rows):
    figs = []
    for (key, title, sub, aria), (ck, els) in zip(ANIMS, anims):
        figs += ['      <figure class="abl-anim ver-anim ver-anim--%s">' % key,
                 f'        <figcaption class="abl-anim__cap"><b>{title}</b><span>{sub}</span></figcaption>',
                 f'<svg class="search-anim" viewBox="0 0 {VB_W} {VB_H}" role="img" aria-label="{aria}">',
                 "\n".join(sa.render(e, "page") for e in els),
                 '</svg>',
                 '      </figure>']
    slide1 = (['  <div class="carousel__slide" data-title="Search guidance">',
               '    <div class="ver-anims">'] + figs + ['    </div>',
               '    <div class="abl-legend"><span><i class="k-pass"></i>verifier pass / high score</span>'
               '<span><i class="k-fail"></i>verifier fail / low score</span><span><i class="k-roll"></i>rollout '
               '(discarded)</span><span><i class="k-win"></i>accepted trajectory</span></div>']
              + ["    " + ln for ln in search_charts(ks, search)] + ['  </div>'])
    slide2 = (['  <div class="carousel__slide" data-title="Success detection">']
              + ["    " + ln for ln in detect_chart(cols, rows)] + ['  </div>'])
    return "\n".join([
        BEGIN_H,
        '<div class="carousel" data-carousel>',
        '  <div class="carousel__bar">',
        '    <button class="carousel__arrow" type="button" data-dir="-1" aria-label="Previous">&larr;</button>',
        '    <p class="carousel__head" aria-live="polite"><span class="carousel__name">Search guidance</span>'
        '<span class="carousel__count">1 / 2</span></p>',
        '    <button class="carousel__arrow" type="button" data-dir="1" aria-label="Next">&rarr;</button>',
        '  </div>'] + slide1 + slide2 + ['</div>', END_H])


def css_for(x, ck):
    decl = [f"animation-name: {x.uid};"]
    if "s" in x.tracks:
        cx, cy = x.origin
        decl += ["transform-box: view-box;", f"transform-origin: {f(cx)}px {f(cy)}px;"]
    if "d" in x.tracks:
        decl.append(f"stroke-dasharray: {x.dash};")
    hold = [sa.PROP_CSS[p](x.value(p, ck.hold)) for p in x.tracks]
    out = [f"#{x.uid} {{ " + " ".join(decl + hold) + " }", f"@keyframes {x.uid} {{"]
    for t in sorted({t for tr in x.tracks.values() for t, _ in tr}):
        parts = [sa.PROP_CSS[p](v) for p, tr in x.tracks.items() for tt, v in tr if abs(tt - t) < 1e-9]
        out.append(f"  {ck.pct(t)} {{ " + " ".join(parts) + " }")
    out.append("}")
    return "\n".join(out)


def css_block(anims):
    static = f"""{BEGIN_C}
.ver-anims {{
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
  margin-bottom: 10px;
}}

@media (max-width: 900px) {{
  .ver-anims {{
    grid-template-columns: 1fr;
  }}
}}

.ver-anim .abl-anim__cap {{
  min-height: 2.9em;
  align-content: flex-start;
}}

.abl-legend .k-roll {{
  background: transparent;
  box-shadow: none;
  border: 1.5px dashed #8892A6;
}}

.ver-table {{
  margin-top: 26px;
}}

/* The K columns sit on a second header row, where "K <= 4" is that row's first
   cell and would pick up the global left alignment meant for row labels. */
.ver-table thead tr + tr th:first-child {{
  text-align: right;
}}

.ver-rules__title {{
  font-family: var(--mono);
  font-size: 0.8rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--head);
  margin: 26px 0 8px;
}}

.ver-rules {{
  margin: 0;
  padding-left: 1.2em;
  font-size: 0.92rem;
  line-height: 1.6;
  color: var(--ink);
}}

.ver-rules li + li {{
  margin-top: 6px;
}}

/* Each animation loops on its own clock; timing is baked into each element's keyframes. */
.ver-anim .va {{
  animation-timing-function: linear;
  animation-iteration-count: infinite;
  animation-fill-mode: both;
}}
""" + "".join(f".ver-anim--{key} .va {{ animation-duration: {f(ck.cycle)}s; }}\n"
             for (key, *_), (ck, _) in zip(ANIMS, anims)) + """
.ver-anim .va-glow {
  filter: drop-shadow(0 0 7px rgba(255, 176, 32, 0.4));
}

.ver-anim .va-goal {
  filter: drop-shadow(0 0 8px rgba(255, 176, 32, 0.55));
}
"""
    rules = "\n".join(css_for(x, ck) for ck, els in anims for x in sa.walk(els))
    tail = f"""
/* Without motion each element rests at its clock's HOLD state: search finished, trajectory lit. */
@media (prefers-reduced-motion: reduce) {{
  .ver-anim .va {{
    animation: none !important;
  }}
}}
{END_C}"""
    return static + "\n" + rules + "\n" + tail


def patch_html(path, block):
    h = path.read_text()
    p0 = h.index('id="panel-abl-verifier"')
    p1 = h.find('id="panel-abl-', p0 + 10)
    p1 = len(h) if p1 == -1 else p1
    ind = "        "
    new = "\n".join((ind + ln) if ln.strip() else ln for ln in block.split("\n"))
    if BEGIN_H in h[p0:p1]:
        a = h.index(BEGIN_H, p0)
        b = h.index(END_H, a) + len(END_H)
    else:
        a = h.index('<div class="media media--placeholder">', p0)
        assert a < p1, "placeholder not inside #panel-abl-verifier"
        b = h.index("</div>", h.index("placeholder__text", a)) + len("</div>")
    a = h.rindex("\n", 0, a) + 1
    path.write_text(h[:a] + new + h[b:])


def patch_css(path, block):
    c = path.read_text()
    if BEGIN_C in c:
        a, b = c.index(BEGIN_C), c.index(END_C) + len(END_C)
        c = c[:a] + block + c[b:]
    else:
        c = c.rstrip("\n") + "\n\n" + block + "\n"
    path.write_text(c)


def frames(outdir, anims, n=8):
    import cairosvg
    from PIL import Image, ImageDraw
    cols = []
    for ck, els in anims:
        tiles = []
        for i in range(n):
            t = ck.cycle * (i + 0.5) / n if i < n - 1 else ck.hold
            svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VB_W} {VB_H}" width="{VB_W}" '
                   f'height="{VB_H}"><rect width="100%" height="100%" fill="{SPACE}"/>'
                   + "".join(sa.render(e, "frame", t) for e in els) + "</svg>")
            img = Image.open(io.BytesIO(cairosvg.svg2png(bytestring=svg.encode()))).convert("RGB")
            tile = Image.new("RGB", (VB_W, VB_H + 18), "white")
            ImageDraw.Draw(tile).text((6, 3), f"t = {t:.1f} / {ck.cycle:.1f} s", fill=(20, 20, 20))
            tile.paste(img, (0, 18))
            tiles.append(tile)
        cols.append(tiles)
    gap = 12
    tw, th = cols[0][0].size
    sheet = Image.new("RGB", (len(cols) * tw + (len(cols) - 1) * gap, n * th + (n - 1) * gap), (150, 156, 166))
    for c, tiles in enumerate(cols):
        for r, tile in enumerate(tiles):
            sheet.paste(tile, (c * (tw + gap), r * (th + gap)))
    outdir.mkdir(parents=True, exist_ok=True)
    p = outdir / "verifier_ablation_frames.png"
    sheet.save(p)
    return p


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--html", type=Path, default=DEF_HTML)
    ap.add_argument("--css", type=Path, default=DEF_CSS)
    ap.add_argument("--frames", type=Path)
    args = ap.parse_args()
    ks, search, cols, rows = parse_tex()
    secs = {s[0]: s[2] for s in search}
    names = [a[1] for a in ANIMS]
    if set(names) != set(secs):
        sys.exit("animation configs %s do not match the paper's %s" % (names, list(secs)))
    anims = [build_verifier(secs[names[0]]), build_uniform(secs[names[1]]), build_rollout(secs[names[2]])]
    ids = [x.uid for _, els in anims for x in sa.walk(els)]
    assert len(ids) == len(set(ids)), "duplicate element ids"
    block = html_block(anims, ks, search, cols, rows).replace('class="sa', 'class="va')
    patch_html(args.html, block)
    cb = css_block(anims)
    patch_css(args.css, cb)
    print("cycles:", ", ".join(f"{n} {ck.cycle:.1f}s" for n, (ck, _) in zip(names, anims)))
    print(f"{len(ids)} animated elements, css block {len(cb) / 1024:.1f} KB")
    if args.frames:
        print("frames:", frames(args.frames, anims))


if __name__ == "__main__":
    main()
